import type { AnimatedExplainer } from "./knowledge-bank";
import { EXPLAINERS_2 } from "./explainers-data-2";
import { EXPLAINERS_3 } from "./explainers-data-3";

const EXPLAINERS_1: AnimatedExplainer[] = [
  // --- IT-GRUNDERNA ---
  {
    id: "hur-fungerar-kryptering",
    title: "Hur fungerar kryptering?",
    description: "Från klartext till hemlig kod och tillbaka.",
    category: "it-grunderna",
    steps: [
      { id: "k1", label: "Klartext", description: "Du skriver ett meddelande: 'Hej, mötet är kl 14.' — läsbart för alla.", icon: "FileText" },
      { id: "k2", label: "Kryptering", description: "En matematisk algoritm och en hemlig nyckel omvandlar texten till oläslig kod.", icon: "KeyRound" },
      { id: "k3", label: "Chiffertext", description: "Meddelandet ser nu ut som: 'xK9#mP2!qR...' — helt obegripligt utan nyckeln.", icon: "Lock" },
      { id: "k4", label: "Överföring", description: "Den krypterade texten skickas via internet. Även om någon fångar upp den kan de inte läsa den.", icon: "Wifi" },
      { id: "k5", label: "Dekryptering", description: "Mottagaren använder sin nyckel för att omvandla tillbaka till klartext.", icon: "Unlock" },
      { id: "k6", label: "Läsbar igen", description: "Mottagaren läser: 'Hej, mötet är kl 14.' — precis som du skrev det.", icon: "Check" },
    ],
  },
  {
    id: "vad-ar-molnet",
    title: "Vad är molnet?",
    description: "Lokal dator vs. molnserver — hur dina filer finns överallt.",
    category: "it-grunderna",
    steps: [
      { id: "m1", label: "Lokalt", description: "Traditionellt: filer sparas på din dator. Bara du kan komma åt dem, från den enheten.", icon: "HardDrive" },
      { id: "m2", label: "Uppladdning", description: "Du sparar filen i molnet (OneDrive, Google Drive). Den krypteras och laddas upp via internet.", icon: "Upload" },
      { id: "m3", label: "Molnservrar", description: "Filen lagras på servrar i datacenter — ofta med kopior på flera platser för säkerhet.", icon: "Server" },
      { id: "m4", label: "Tillgänglig överallt", description: "Nu kan du nå filen från din dator, telefon eller surfplatta — var du än är.", icon: "Smartphone" },
      { id: "m5", label: "Synkronisering", description: "Ändrar du filen på en enhet uppdateras den automatiskt på alla andra.", icon: "RefreshCw" },
    ],
  },
  {
    id: "hur-fungerar-internet",
    title: "Hur fungerar internet?",
    description: "Vad händer när du besöker en webbsida.",
    category: "it-grunderna",
    steps: [
      { id: "i1", label: "Du skriver en URL", description: "Du skriver 'aihubben.se' i webbläsaren och trycker Enter.", icon: "Globe" },
      { id: "i2", label: "DNS-uppslag", description: "DNS översätter 'aihubben.se' till en IP-adress (t.ex. 185.32.10.1) — som att slå upp ett nummer i telefonboken.", icon: "BookOpen" },
      { id: "i3", label: "Förfrågan skickas", description: "Din dator skickar en förfrågan via internet till servern på den IP-adressen.", icon: "Send" },
      { id: "i4", label: "Servern svarar", description: "Servern hittar rätt sida och skickar tillbaka HTML, CSS och bilder i små datapaket.", icon: "Server" },
      { id: "i5", label: "Sidan visas", description: "Din webbläsare sätter ihop alla delar och visar den färdiga sidan. Allt på millisekunder.", icon: "Monitor" },
    ],
  },
  {
    id: "vad-hander-vid-2fa",
    title: "Vad händer vid 2FA-inloggning?",
    description: "Två bevis på att du är du.",
    category: "it-grunderna",
    steps: [
      { id: "t1", label: "Lösenord", description: "Du skriver ditt lösenord — det första beviset (något du vet).", icon: "KeyRound" },
      { id: "t2", label: "Server kollar", description: "Servern verifierar lösenordet. Rätt! Men det räcker inte — någon kan ha stulit det.", icon: "Server" },
      { id: "t3", label: "Kod skickas", description: "En engångskod skickas till din telefon via SMS eller app — det andra beviset (något du har).", icon: "Smartphone" },
      { id: "t4", label: "Du matar in koden", description: "Du skriver in koden. Servern verifierar att den stämmer och inte gått ut.", icon: "Check" },
      { id: "t5", label: "Inloggad!", description: "Båda bevis godkända. Du släpps in. Även om någon stulit ditt lösenord behöver de din telefon också.", icon: "ShieldCheck" },
    ],
  },
  {
    id: "vad-ar-databas",
    title: "Vad är en databas?",
    description: "Från kaos till organiserad, sökbar information.",
    category: "it-grunderna",
    steps: [
      { id: "d1", label: "Kaotisk data", description: "Tänk dig tusentals lösa papper med information — omöjligt att hitta något snabbt.", icon: "Files" },
      { id: "d2", label: "Organiserade tabeller", description: "En databas ordnar all data i tabeller med rader och kolumner — som ett supersnabbt Excel.", icon: "Table" },
      { id: "d3", label: "Du ställer en fråga", description: "'Visa alla ärenden från januari som gäller bygglov.' Databasen förstår din fråga.", icon: "Search" },
      { id: "d4", label: "Svar på millisekunder", description: "Databasen söker igenom miljontals rader och returnerar exakt det du frågade om — blixtsnabbt.", icon: "Zap" },
    ],
  },

  // --- AI-GRUNDERNA ---
  {
    id: "hur-lar-sig-en-ai",
    title: "Hur lär sig en AI?",
    description: "Från data till kunskap — AI:ns inlärningsprocess.",
    category: "ai-grunderna",
    steps: [
      { id: "a1", label: "Träningsdata", description: "AI:n matas med enorma mängder data — miljarder texter, böcker, webbsidor. Dess 'skolmaterial'.", icon: "FileStack" },
      { id: "a2", label: "Mönsterigenkänning", description: "AI:n hittar mönster: 'efter ordet Katrineholm kommer ofta kommun'. Den lär sig språkets struktur.", icon: "Eye" },
      { id: "a3", label: "Justering", description: "AI:n gissar, kollar om den hade rätt, och justerar. Miljontals gånger. Varje gång blir den lite bättre.", icon: "SlidersHorizontal" },
      { id: "a4", label: "Färdig modell", description: "Efter veckor/månader av träning: en modell med miljarder inlärda mönster, redo att svara på frågor.", icon: "Box" },
      { id: "a5", label: "Ny input", description: "Du ställer en fråga den aldrig sett förut. Tack vare mönstren kan den generera ett relevant svar.", icon: "MessageSquare" },
    ],
  },
  {
    id: "vad-ar-neuralt-natverk",
    title: "Vad är ett neuralt nätverk?",
    description: "Lager av noder som bearbetar information.",
    category: "ai-grunderna",
    steps: [
      { id: "n1", label: "Input-lager", description: "Data matas in — t.ex. en mening. Varje ord blir en siffra som skickas in i nätverket.", icon: "ArrowRight" },
      { id: "n2", label: "Gömda lager", description: "Informationen passerar genom lager av sammankopplade noder. Varje koppling har en vikt (styrka).", icon: "Network" },
      { id: "n3", label: "Bearbetning", description: "Varje nod gör en liten beräkning och skickar resultatet vidare. Miljontals beräkningar samtidigt.", icon: "Cpu" },
      { id: "n4", label: "Output-lager", description: "Det sista lagret producerar resultatet — t.ex. nästa ord i en mening eller en klassificering.", icon: "ArrowRight" },
      { id: "n5", label: "Justering av vikter", description: "Under träning: om svaret var fel justeras vikterna bakåt genom nätverket (backpropagation).", icon: "RotateCcw" },
    ],
  },
  {
    id: "ai-vs-ml-vs-dl",
    title: "AI vs. ML vs. Deep Learning",
    description: "Tre begrepp som hänger ihop — som ryska dockor.",
    category: "ai-grunderna",
    steps: [
      { id: "amd1", label: "AI — det breda fältet", description: "Artificiell Intelligens: allt som gör att datorer verkar intelligenta. Regler, logik, och lärande.", icon: "Brain" },
      { id: "amd2", label: "ML — en metod inom AI", description: "Maskininlärning: en del av AI där datorn lär sig från data istället för att följa förprogrammerade regler.", icon: "TrendingUp" },
      { id: "amd3", label: "DL — en typ av ML", description: "Deep Learning: maskininlärning med djupa neurala nätverk — många lager som lär sig allt mer komplexa mönster.", icon: "Layers" },
      { id: "amd4", label: "LLM — en tillämpning av DL", description: "Språkmodeller som GPT och Claude är byggda med deep learning, tränade på text för att förstå och generera språk.", icon: "BookText" },
    ],
  },

  // --- SPRÅKMODELLER ---
  {
    id: "prompt-till-svar",
    title: "Från prompt till svar",
    description: "Vad händer inuti AI:ns hjärna när du ställer en fråga.",
    category: "sprakmodeller",
    steps: [
      { id: "p1", label: "Du skriver en prompt", description: "'Vad är artificiell intelligens?' — din fråga skickas till AI-modellen.", icon: "MessageSquare" },
      { id: "p2", label: "Tokenisering", description: "Texten delas i tokens: ['Vad', ' är', ' art', 'ificiell', ' intell', 'igens', '?']. AI:n läser bitar, inte ord.", icon: "SplitSquareHorizontal" },
      { id: "p3", label: "Embedding", description: "Varje token omvandlas till en vektor (lista med siffror) som fångar dess betydelse.", icon: "Grid3x3" },
      { id: "p4", label: "Attention", description: "Modellen väger vilka tokens som är viktigast för varandra. 'Artificiell' + 'intelligens' hör ihop.", icon: "Focus" },
      { id: "p5", label: "Layer processing", description: "Vektorerna passerar genom 80+ transformer-lager. Varje lager förfinar förståelsen.", icon: "Layers" },
      { id: "p6", label: "Nästa token förutsägs", description: "Modellen beräknar sannolikheten för varje möjligt nästa ord. 'AI' → 'är' → 'ett' → 'område'...", icon: "Sparkles" },
      { id: "p7", label: "Svar genereras", description: "Token för token byggs svaret upp tills modellen producerar ett stopptecken. Du ser svaret strömma in.", icon: "Check" },
    ],
  },
  {
    id: "vad-ar-tokens",
    title: "Vad är tokens?",
    description: "Hur AI:n läser text — inte ord, utan bitar.",
    category: "sprakmodeller",
    steps: [
      { id: "tk1", label: "Du skriver en mening", description: "'Katrineholms kommun satsar på AI' — 6 svenska ord.", icon: "PenTool" },
      { id: "tk2", label: "Tokenisering", description: "AI:n delar texten: ['Kat', 'rine', 'holms', ' kommun', ' s', 'atsar', ' på', ' AI'] — 8 tokens.", icon: "Scissors" },
      { id: "tk3", label: "Varför bitar?", description: "Genom att dela ord i subdelar kan AI:n hantera nya ord den aldrig sett — 'Katrineholm' delas i kända bitar.", icon: "Puzzle" },
      { id: "tk4", label: "Räkna tokens", description: "~1 token ≈ ¾ ord på engelska. Svenska ord är ofta längre = fler tokens. Tokens styr kostnad och hastighet.", icon: "Calculator" },
      { id: "tk5", label: "Kontext-fönster", description: "En modell har plats för ett visst antal tokens (t.ex. 128K). Input + output räknas. Tar texten slut → AI:n 'glömmer'.", icon: "Maximize2" },
    ],
  },
  {
    id: "temperatur-kreativitet",
    title: "Temperatur — kreativitet vs. exakthet",
    description: "En ratt som styr hur AI:n svarar.",
    category: "sprakmodeller",
    steps: [
      { id: "te1", label: "Frågan ställs", description: "Du frågar: 'Vad är huvudstaden i Sverige?' — AI:n beräknar sannolikheter för varje möjligt svar.", icon: "MessageSquare" },
      { id: "te2", label: "Temperatur 0 (exakt)", description: "Väljer alltid det mest sannolika ordet. Svar: 'Stockholm.' Förutsägbart, korrekt, men torrt.", icon: "Target" },
      { id: "te3", label: "Temperatur 0.7 (balanserat)", description: "Blandar säkra och kreativa val. Svar: 'Huvudstaden i Sverige är Stockholm, beläget vid Mälaren.' Mer utförligt.", icon: "SlidersHorizontal" },
      { id: "te4", label: "Temperatur 1.0+ (kreativt)", description: "Tar fler risker. Svar kan bli poetiskt, oväntat — men också felaktigt. Bra för kreativa uppgifter.", icon: "Sparkles" },
      { id: "te5", label: "Tumregel", description: "Fakta & kod → låg temperatur. Kreativ text & brainstorming → hög temperatur. Du väljer vad du behöver.", icon: "Lightbulb" },
    ],
  },
  {
    id: "kontextfonstret",
    title: "Kontext-fönstret",
    description: "AI:ns korttidsminne — vad den kan 'se'.",
    category: "sprakmodeller",
    steps: [
      { id: "kf1", label: "Allt i ett fönster", description: "AI:n ser hela konversationen som en enda text. Din fråga, dess svar, din uppföljning — allt i samma fönster.", icon: "Maximize2" },
      { id: "kf2", label: "Begränsat utrymme", description: "Fönstret har en maxstorlek (t.ex. 128K tokens). Allt som ska läsas OCH skrivas måste rymmas.", icon: "Box" },
      { id: "kf3", label: "Äldre försvinner", description: "I en lång konversation 'faller' tidiga meddelanden ut när fönstret blir fullt. AI:n glömmer.", icon: "ArrowDown" },
      { id: "kf4", label: "Större fönster = mer minne", description: "GPT-4: ~128K tokens. Claude: 200K. Gemini: 1M+. Större fönster = längre konversationer utan att glömma.", icon: "Maximize2" },
    ],
  },

  // --- AI PÅ JOBBET ---
  {
    id: "hur-skriver-du-bra-prompt",
    title: "Hur skriver du en bra prompt?",
    description: "Från vag fråga till tydlig instruktion.",
    category: "ai-pa-jobbet",
    steps: [
      { id: "pr1", label: "Dålig prompt", description: "'Skriv ett mejl.' — AI:n vet inte till vem, om vad, eller vilken ton. Resultatet blir generiskt.", icon: "ThumbsDown" },
      { id: "pr2", label: "Lägg till uppgift", description: "'Skriv ett mejl som informerar om ny parkeringspolicy.' — Nu vet AI:n VAD.", icon: "FileText" },
      { id: "pr3", label: "Lägg till kontext", description: "'...till alla anställda på kommunen. Policyn börjar gälla 1 april.' — Nu vet AI:n VARFÖR och TILL VEM.", icon: "Users" },
      { id: "pr4", label: "Lägg till format", description: "'Max 150 ord, punktlista med de 3 viktigaste ändringarna.' — Nu vet AI:n HUR.", icon: "ListOrdered" },
      { id: "pr5", label: "Lägg till persona & ton", description: "'Skriv som en vänlig HR-ansvarig, professionell men inte byråkratisk.' — Nu vet AI:n VEM.", icon: "UserCheck" },
      { id: "pr6", label: "Bra prompt!", description: "Resultat: ett fokuserat, relevant mejl som knappt behöver redigeras. Bra prompt = bra svar.", icon: "ThumbsUp" },
    ],
  },
  {
    id: "hur-fungerar-transkribering",
    title: "Hur fungerar transkribering?",
    description: "Från tal till text med AI.",
    category: "ai-pa-jobbet",
    steps: [
      { id: "tr1", label: "Ljudupptagning", description: "Du spelar in ett möte eller laddar upp en ljudfil (MP3, WAV).", icon: "Mic" },
      { id: "tr2", label: "Ljudvågor analyseras", description: "AI:n bryter ner ljudet i korta segment och analyserar vågformerna.", icon: "AudioWaveform" },
      { id: "tr3", label: "Tal identifieras", description: "En specialtränad modell (t.ex. Whisper) känner igen ord och skiljer talare åt.", icon: "Brain" },
      { id: "tr4", label: "Text genereras", description: "Resultatet: skriven text med tidsstämplar och (ofta) talarseparation.", icon: "FileText" },
      { id: "tr5", label: "Efterbearbetning", description: "Texten kan sammanfattas, struktureras som protokoll, eller sökas igenom med AI.", icon: "Sparkles" },
    ],
  },
  {
    id: "ai-agent-vs-assistent",
    title: "AI-agent vs. AI-assistent",
    description: "Skillnaden mellan att svara och att agera.",
    category: "ai-pa-jobbet",
    steps: [
      { id: "ag1", label: "AI-assistent", description: "Du frågar → AI svarar → Klart. En fråga, ett svar. Som att fråga en receptionist.", icon: "MessageSquare" },
      { id: "ag2", label: "AI-agent: Planerar", description: "Du ger ett uppdrag: 'Skriv en rapport om kommunens energiförbrukning.' Agenten bryter ner uppgiften.", icon: "ListTodo" },
      { id: "ag3", label: "Agent: Söker info", description: "Steg 1: Agenten söker i kunskapsbaser, databaser och webbkällor efter relevant data.", icon: "Search" },
      { id: "ag4", label: "Agent: Analyserar", description: "Steg 2: Data analyseras, jämförelser görs, trender identifieras.", icon: "TrendingUp" },
      { id: "ag5", label: "Agent: Skriver", description: "Steg 3: Agenten skriver rapporten med källhänvisningar och diagram.", icon: "PenTool" },
      { id: "ag6", label: "Agent: Levererar", description: "Du får en färdig rapport. Agenten gjorde flera steg självständigt — du behövde bara ge uppdraget.", icon: "Check" },
    ],
  },

  // --- INTRIC & VERKTYG ---
  {
    id: "intric-dataflode",
    title: "Vad händer med din data i Intric?",
    description: "Dataflödet från fråga till svar — inom EU.",
    category: "intric",
    steps: [
      { id: "id1", label: "Du ställer en fråga", description: "Du skriver i Intric-chatten: 'Vad säger vår resepolicy om hotellbokning?'", icon: "MessageSquare" },
      { id: "id2", label: "Intric-server (EU)", description: "Frågan skickas till Intrics servrar i EU/EES — aldrig utanför Europa.", icon: "Server" },
      { id: "id3", label: "Säkerhetsklass kollas", description: "Spacets säkerhetsklass bestämmer vilka AI-modeller som får användas för just denna data.", icon: "ShieldCheck" },
      { id: "id4", label: "RAG-sökning", description: "Intric söker i din kunskapsbas efter relevanta avsnitt om resepolicy.", icon: "Search" },
      { id: "id5", label: "Modellen svarar", description: "Din fråga + relevanta dokumentavsnitt skickas till AI-modellen som genererar ett förankrat svar.", icon: "Sparkles" },
      { id: "id6", label: "Data retention", description: "Konversationen sparas enligt din inställning (7/30/365 dagar) och raderas sedan permanent.", icon: "Clock" },
    ],
  },
  {
    id: "chatgpt-vs-intric",
    title: "ChatGPT vs. Intric",
    description: "Vad händer med din data i respektive tjänst.",
    category: "intric",
    steps: [
      { id: "ci1", label: "Du ställer samma fråga", description: "'Sammanfatta vår personalhandbok' — i ChatGPT och i Intric.", icon: "MessageSquare" },
      { id: "ci2", label: "ChatGPT: Data → USA", description: "Din fråga skickas till OpenAI:s servrar i USA. Kan loggas och lagras. Tredjelandsöverföring.", icon: "Globe" },
      { id: "ci3", label: "Intric: Data → EU", description: "Din fråga stannar i EU/EES på Intrics certifierade servrar. Aldrig till USA.", icon: "ShieldCheck" },
      { id: "ci4", label: "ChatGPT: Inget RAG", description: "ChatGPT har inte tillgång till er personalhandbok. Svaret blir generellt eller felaktigt.", icon: "AlertTriangle" },
      { id: "ci5", label: "Intric: RAG-sökning", description: "Intric söker i er uppladdade handbok och ger svar baserade på ER data.", icon: "BookSearch" },
      { id: "ci6", label: "Skillnaden", description: "Intric: GDPR-säkert, verksamhetsspecifikt, kontrollerbart. ChatGPT: brett men opålitligt för intern data.", icon: "Scale" },
    ],
  },
  {
    id: "ladda-upp-dokument-intric",
    title: "Ladda upp dokument i Intric",
    description: "Från PDF till sökbar kunskap.",
    category: "intric",
    steps: [
      { id: "lu1", label: "Du laddar upp en PDF", description: "Du drar personalhandboken (PDF) till en Samling i ditt Space.", icon: "Upload" },
      { id: "lu2", label: "OCR (om skannat)", description: "Om dokumentet är skannat körs OCR — AI läser texten i bilden och gör den digital.", icon: "ScanText" },
      { id: "lu3", label: "Text extraheras", description: "All text plockas ut ur dokumentet — rubriker, brödtext, tabeller.", icon: "FileText" },
      { id: "lu4", label: "Chunking", description: "Texten delas i mindre bitar (chunks) — ungefär ett stycke var. Varje bit hanteras separat.", icon: "Scissors" },
      { id: "lu5", label: "Embedding", description: "Varje bit omvandlas till en vektor (siffror) som fångar betydelsen. Lagras i vektordatabasen.", icon: "Grid3x3" },
      { id: "lu6", label: "Redo att söka!", description: "Nu kan din assistent söka i dokumentet med semantisk sökning. 'Vad gäller för semester?' hittar rätt avsnitt.", icon: "Check" },
    ],
  },
  {
    id: "copilot-i-outlook",
    title: "Copilot i Outlook",
    description: "Vad händer bakom kulisserna.",
    category: "copilot",
    steps: [
      { id: "co1", label: "Du klickar Copilot", description: "I Outlook klickar du Copilot-ikonen och skriver: 'Skriv ett artigt svar som tackar nej till mötet.'", icon: "Mouse" },
      { id: "co2", label: "Microsoft Graph", description: "Copilot hämtar kontext: mejltråden, din kalender, relevanta dokument från OneDrive/SharePoint.", icon: "GitBranch" },
      { id: "co3", label: "Semantic Index", description: "Microsofts sökindex hittar relevant information baserat på betydelse, inte bara nyckelord.", icon: "Search" },
      { id: "co4", label: "Prompt byggs", description: "Din instruktion + relevant kontext packas ihop till en prompt som skickas till LLM:en (Azure OpenAI).", icon: "Package" },
      { id: "co5", label: "Svar genereras", description: "AI:n genererar ett mejlutkast som är kontextuellt relevant — den vet vem du mejlar och varför.", icon: "Sparkles" },
      { id: "co6", label: "Du redigerar", description: "Utkastet visas. Du justerar ton och detaljer, och skickar. Copilot assisterar — du bestämmer.", icon: "PenTool" },
    ],
  },
  {
    id: "copilot-i-teams",
    title: "Copilot i Teams-möte",
    description: "Transkribering, sammanfattning och frågor.",
    category: "copilot",
    steps: [
      { id: "ct1", label: "Mötet börjar", description: "Du startar ett Teams-möte med Copilot aktiverat. Transkribering körs i bakgrunden.", icon: "Video" },
      { id: "ct2", label: "Realtidstranskribering", description: "Allt som sägs omvandlas till text i realtid. Talare identifieras automatiskt.", icon: "Mic" },
      { id: "ct3", label: "Du frågar Copilot", description: "Under mötet kan du fråga: 'Vad har vi diskuterat om budgeten hittills?'", icon: "MessageSquare" },
      { id: "ct4", label: "Copilot sammanfattar", description: "Copilot analyserar transkriptionen och ger en strukturerad sammanfattning med beslutspunkter.", icon: "ListTodo" },
      { id: "ct5", label: "Mötet slutar", description: "Du får: komplett transkription + sammanfattning + åtgärdspunkter med ansvariga. Sparat i Teams.", icon: "Check" },
    ],
  },

  // --- TEKNIK & INTEGRATION ---
  {
    id: "vad-ar-mcp",
    title: "Vad är en MCP-server?",
    description: "Universal adapter som kopplar AI till datakällor.",
    category: "teknik",
    steps: [
      { id: "mc1", label: "AI:n behöver data", description: "Din AI-assistent vill svara: 'Hur många bor i Katrineholm?' — men den har inte statistik inbyggd.", icon: "Bot" },
      { id: "mc2", label: "Utan MCP", description: "Du måste bygga en unik koppling till varje datakälla — SCB, Kolada, Skolverket. Dyrt och tidskrävande.", icon: "AlertTriangle" },
      { id: "mc3", label: "MCP = Universal adapter", description: "Model Context Protocol är en öppen standard. En koppling som fungerar med alla datakällor.", icon: "Cable" },
      { id: "mc4", label: "Anslut datakällor", description: "MCP-servrar finns för SCB, Kolada, Domstolsverket, Socialstyrelsen — och fler kommer.", icon: "Database" },
      { id: "mc5", label: "AI:n hämtar data", description: "Assistenten anropar MCP-servern → MCP kontaktar datakällan → Aktuell data returneras.", icon: "ArrowRightLeft" },
      { id: "mc6", label: "Svar med riktiga fakta", description: "'Katrineholm har 35 200 invånare (SCB, 2025)' — svar baserade på aktuell data, inte AI-gissningar.", icon: "Check" },
    ],
  },
  {
    id: "mcp-scb-kolada",
    title: "MCP: SCB och Kolada i praktiken",
    description: "Statistikfrågor besvarade med aktuell myndighetsdata.",
    category: "teknik",
    steps: [
      { id: "ms1", label: "Frågan", description: "'Hur ligger Katrineholm till jämfört med liknande kommuner vad gäller sjukfrånvaro?' — ställd i Intric.", icon: "MessageSquare" },
      { id: "ms2", label: "Intric förstår", description: "Assistenten identifierar att den behöver statistik — och att Kolada MCP-servern kan hjälpa.", icon: "Brain" },
      { id: "ms3", label: "MCP anropas", description: "Assistenten skickar en strukturerad förfrågan till Kolada MCP-servern: 'sjukfrånvaro, Katrineholm, jämförelsegrupp'.", icon: "Send" },
      { id: "ms4", label: "Data hämtas", description: "MCP-servern hämtar aktuell statistik direkt från Koladas API — uppdaterade siffror.", icon: "Database" },
      { id: "ms5", label: "AI sammanfattar", description: "Assistenten formulerar ett tydligt svar med jämförelsesiffror och trender — baserat på riktiga data.", icon: "Sparkles" },
    ],
  },
  {
    id: "mcp-skolverket",
    title: "MCP: Skolverket/Domstolsverket",
    description: "Läroplaner och rättspraxis via AI.",
    category: "teknik",
    steps: [
      { id: "msk1", label: "Rektorn frågar", description: "'Vilka krav ställer den nya läroplanen på digital kompetens i årskurs 4-6?'", icon: "MessageSquare" },
      { id: "msk2", label: "MCP kontaktar Skolverket", description: "Assistenten anropar Skolverkets MCP-server för att hämta relevanta avsnitt ur läroplanen.", icon: "Send" },
      { id: "msk3", label: "Relevant information hämtas", description: "MCP-servern returnerar specifika paragrafer och kursplaneavsnitt om digital kompetens.", icon: "FileText" },
      { id: "msk4", label: "AI sammanfattar", description: "Assistenten sammanfattar kraven och ger konkreta förslag på hur skolan kan uppfylla dem.", icon: "Sparkles" },
      { id: "msk5", label: "Med källhänvisning", description: "Svaret inkluderar hänvisning till exakt paragraf och kapitel — verifierbart och pålitligt.", icon: "Check" },
    ],
  },
  {
    id: "hur-fungerar-api",
    title: "Hur fungerar en API?",
    description: "Restauranganalogin — animerad.",
    category: "teknik",
    steps: [
      { id: "ap1", label: "Du (klienten)", description: "Du sitter på en restaurang och vet vad du vill ha. Men du kan inte gå in i köket själv.", icon: "User" },
      { id: "ap2", label: "Servitören (API:t)", description: "Du ger din beställning till servitören. Servitören är gränssnittet — den som tar emot och levererar.", icon: "ArrowRightLeft" },
      { id: "ap3", label: "Köket (servern)", description: "Servitören lämnar beställningen till köket. Köket lagar maten — den tunga bearbetningen.", icon: "Server" },
      { id: "ap4", label: "Maten levereras", description: "Servitören hämtar den färdiga rätten och serverar den till dig. Du behöver inte veta hur köket fungerar.", icon: "Check" },
      { id: "ap5", label: "I verkligheten", description: "Din app (du) → API (servitör) → Server (kök) → Svar (mat). Alla appar och AI-tjänster kommunicerar så här.", icon: "Globe" },
    ],
  },
  {
    id: "hur-fungerar-integration",
    title: "Hur fungerar en integration?",
    description: "Manuellt vs. automatiskt — före och efter.",
    category: "teknik",
    steps: [
      { id: "in1", label: "Utan integration", description: "HR-systemet och lönesystemet pratar inte med varandra. Du kopierar data manuellt mellan dem.", icon: "Copy" },
      { id: "in2", label: "Manuellt arbete", description: "Ny anställd? Mata in samma uppgifter i 5 olika system. Tidskrävande och felbenäget.", icon: "Clock" },
      { id: "in3", label: "Med integration", description: "Systemen kopplas ihop via API:er. Data flödar automatiskt mellan dem.", icon: "Link2" },
      { id: "in4", label: "Automatiskt flöde", description: "Ny anställd registreras i HR → lönesystem, behörigheter och mejlkonto skapas automatiskt.", icon: "Zap" },
      { id: "in5", label: "Intric-integration", description: "Intric kan kopplas till SharePoint, Teams, Google Workspace — din AI-assistent får tillgång till befintlig data.", icon: "Boxes" },
    ],
  },
  {
    id: "lokal-vs-moln-ai",
    title: "Lokal AI vs. moln-AI",
    description: "Sida vid sida — fördelar och nackdelar.",
    category: "teknik",
    steps: [
      { id: "lm1", label: "Moln-AI", description: "Din fråga skickas via internet till leverantörens servrar (OpenAI, Google). De kör modellen och skickar svar.", icon: "Cloud" },
      { id: "lm2", label: "Moln: Fördelar", description: "Enkel att starta, ingen egen hårdvara, alltid uppdaterad, kraftfullaste modellerna.", icon: "ThumbsUp" },
      { id: "lm3", label: "Moln: Nackdelar", description: "Data lämnar organisationen, kostnad per fråga, beroende av leverantör, GDPR-risk vid tredjeland.", icon: "AlertTriangle" },
      { id: "lm4", label: "Lokal AI", description: "Modellen körs på din egen server. Inget skickas till internet. All data stannar inom nätverket.", icon: "Server" },
      { id: "lm5", label: "Lokal: Fördelar", description: "Full datakontroll, ingen GDPR-risk, ingen leverantörsinlåsning, fungerar offline.", icon: "ShieldCheck" },
      { id: "lm6", label: "Lokal: Nackdelar", description: "Kräver dyr GPU-hårdvara, IT-kompetens, modellerna kan vara mindre kapabla.", icon: "AlertTriangle" },
      { id: "lm7", label: "Bäst av båda?", description: "Intric: EU-hostade modeller, eller on-premises. GDPR-säkert med molnets enkelhet.", icon: "Check" },
    ],
  },

  // --- DATA & SÖKNING ---
  {
    id: "hur-fungerar-rag",
    title: "Hur fungerar RAG?",
    description: "Svar baserade på dina egna dokument.",
    category: "data-sokning",
    steps: [
      { id: "r1", label: "Förberedelse: Dokument", description: "Dina dokument (PDF, Word, webbsidor) laddas upp i systemet.", icon: "FileStack" },
      { id: "r2", label: "Förberedelse: Chunking", description: "Dokumenten delas i mindre bitar (chunks) — ungefär ett stycke var.", icon: "Scissors" },
      { id: "r3", label: "Förberedelse: Embedding", description: "Varje bit omvandlas till vektorer (siffror som fångar betydelsen) och lagras i en vektordatabas.", icon: "Grid3x3" },
      { id: "r4", label: "Fråga: Du frågar", description: "'Vad säger vår resepolicy om flygresor?' — din fråga skickas till RAG-systemet.", icon: "MessageSquare" },
      { id: "r5", label: "Fråga: Sökning", description: "Din fråga omvandlas till en vektor och jämförs mot alla lagrade bitar. De mest relevanta hittas.", icon: "Search" },
      { id: "r6", label: "Fråga: Kontext + LLM", description: "De relevanta bitarna + din fråga skickas till språkmodellen som formulerar ett svar baserat på DINA dokument.", icon: "Sparkles" },
      { id: "r7", label: "Resultat", description: "Du får ett svar som är förankrat i din kunskapsbas — inte AI-gissningar. Mindre hallucinationer, mer pålitligt.", icon: "Check" },
    ],
  },
  {
    id: "semantisk-vs-nyckelord",
    title: "Semantisk sökning vs. nyckelord",
    description: "Söka efter betydelse, inte bara exakta ord.",
    category: "data-sokning",
    steps: [
      { id: "sv1", label: "Du söker", description: "'Hur minskar vi energikostnader?' — du vill hitta relevant information.", icon: "Search" },
      { id: "sv2", label: "Nyckelordssökning", description: "Letar efter exakt dessa ord. Hittar dokument med 'energikostnader' men MISSAR 'elförbrukning', 'energieffektivisering'.", icon: "FileSearch" },
      { id: "sv3", label: "Semantisk sökning", description: "Förstår BETYDELSEN. Hittar även: 'minska elförbrukning', 'energieffektivisering', 'sänka driftkostnader'.", icon: "Brain" },
      { id: "sv4", label: "Hur fungerar det?", description: "Alla texter omvandlas till vektorer (siffror). Texter med liknande MENING hamnar nära varandra — oavsett ordval.", icon: "Grid3x3" },
      { id: "sv5", label: "Resultat", description: "Du hittar fler och mer relevanta dokument. Intrics kunskapssökning och Microsofts Semantic Index använder detta.", icon: "Check" },
    ],
  },
  {
    id: "vad-ar-embeddings",
    title: "Vad är embeddings?",
    description: "Ord som koordinater på en betydelsekarta.",
    category: "data-sokning",
    steps: [
      { id: "e1", label: "Text som text", description: "Datorer förstår siffror, inte ord. 'Kung' och 'Drottning' är bara bokstäver för en dator.", icon: "FileText" },
      { id: "e2", label: "Text → Siffror", description: "En embeddingmodell omvandlar varje ord/mening till en lista med siffror (en vektor). T.ex. [0.23, -0.87, 0.41...].", icon: "Binary" },
      { id: "e3", label: "Betydelsekarta", description: "Vektorer som representerar liknande ord hamnar nära varandra. 'Kung' och 'Drottning' är grannar på kartan.", icon: "Map" },
      { id: "e4", label: "'Kung' - 'Man' + 'Kvinna' = ?", description: "Det berömda exemplet: om du gör den matematiska operationen i vektorrummet landar du nära 'Drottning'.", icon: "Calculator" },
      { id: "e5", label: "Användning", description: "Embeddings är grunden för RAG, semantisk sökning och rekommendationssystem. Intric använder dem i alla kunskapsbaser.", icon: "Sparkles" },
    ],
  },

  // --- LAGAR & SÄKERHET ---
  {
    id: "ai-act-riskkategorier-animation",
    title: "EU AI Act — riskkategorier",
    description: "Pyramid från minimal risk till förbjudet.",
    category: "lagar-regler",
    steps: [
      { id: "aa1", label: "Minimal risk (bas)", description: "Spamfilter, AI-spel, rekommendationssystem. Inga specifika krav. Fri användning.", icon: "Check" },
      { id: "aa2", label: "Begränsad risk", description: "Chatbotar, AI-genererad text/bild. Krav: transparens — användare måste veta att det är AI. Gäller kommunens chatbotar.", icon: "Eye" },
      { id: "aa3", label: "Hög risk", description: "AI i rekrytering, utbildning, socialtjänst, rättsväsende. Krav: DPIA, dokumentation, mänsklig kontroll, CE-märkning. Gäller flera kommunala verksamheter.", icon: "AlertTriangle" },
      { id: "aa4", label: "Förbjudet (topp)", description: "Social scoring, manipulativ AI, massövervakning med ansiktsigenkänning. Helt bannlyst sedan feb 2025.", icon: "Ban" },
      { id: "aa5", label: "Vad gäller för kommunen?", description: "De flesta kommunala AI-användningar: begränsad eller hög risk. Transparens och mänsklig kontroll är nyckelkrav.", icon: "Building2" },
    ],
  },

  // --- NYA IT-GRUNDERNA ---
  {
    id: "server",
    title: "Vad är en server?",
    description: "Datorn som aldrig sover — den serverar dig.",
    category: "it-grunderna",
    steps: [
      { id: "srv1", label: "Vanlig dator", description: "Din dator hemma eller på jobbet använder du själv. Den är avstängd när du går hem.", icon: "Monitor" },
      { id: "srv2", label: "En server = en tjänare", description: "En server är en dator som är igång dygnet runt och väntar på förfrågningar från andra datorer. Namnet betyder bokstavligen 'tjänare'.", icon: "Server" },
      { id: "srv3", label: "Du skickar en förfrågan", description: "När du besöker en webbsida skickar din webbläsare en förfrågan till en server. Servern hämtar rätt filer och skickar tillbaka dem.", icon: "Send" },
      { id: "srv4", label: "Många användare samtidigt", description: "Till skillnad från din dator kan en server hantera tusentals förfrågningar samtidigt — från människor världen över.", icon: "Users" },
      { id: "srv5", label: "Datacenter", description: "Servrar står i stora hallar (datacenter) med kylning, backup-ström och säkerhet. Där bor webbsidor, e-post och molntjänster.", icon: "Building2" },
    ],
  },
  {
    id: "webblasare",
    title: "Vad är en webbläsare?",
    description: "Ditt fönster till internet.",
    category: "it-grunderna",
    steps: [
      { id: "wbl1", label: "Programmet du surfar med", description: "Chrome, Edge, Firefox, Safari — alla är webbläsare. Det är programmet du öppnar för att besöka webbsidor.", icon: "Globe" },
      { id: "wbl2", label: "Du skriver en adress", description: "Du skriver 'aihubben.se' i adressfältet. Webbläsaren skickar en förfrågan till rätt server.", icon: "Search" },
      { id: "wbl3", label: "Kod tolkas", description: "Servern skickar tillbaka kod (HTML, CSS, JavaScript). Webbläsaren översätter koden till den sida du ser — knappar, bilder, text.", icon: "Code" },
      { id: "wbl4", label: "Interaktion", description: "Du klickar, scrollar och fyller i formulär. Webbläsaren hanterar allt och kommunicerar med servern i bakgrunden.", icon: "MousePointer" },
    ],
  },
  {
    id: "url",
    title: "Vad är en URL?",
    description: "Webbens adresssystem — som en gatuadress, fast digital.",
    category: "it-grunderna",
    steps: [
      { id: "url1", label: "En webbadress", description: "URL står för Uniform Resource Locator. Det är adressen till en specifik sida på internet, t.ex. 'https://aihubben.se/utbildning'.", icon: "Link2" },
      { id: "url2", label: "Protokoll", description: "Första delen, 'https://', talar om HUR din webbläsare ska kommunicera med servern — krypterat och säkert.", icon: "Lock" },
      { id: "url3", label: "Domännamn", description: "'aihubben.se' är domännamnet — som en gatuadress. Det pekar på rätt server bland miljontals servrar.", icon: "Globe" },
      { id: "url4", label: "Sökväg", description: "'/utbildning' säger VILKEN sida på servern du vill se. Utan sökväg får du startsidan.", icon: "FolderOpen" },
    ],
  },
  {
    id: "http-https",
    title: "HTTP vs. HTTPS",
    description: "Varför det lilla hänglåset i webbläsaren är viktigt.",
    category: "it-grunderna",
    steps: [
      { id: "ht1", label: "HTTP — öppen kommunikation", description: "HTTP skickar data mellan din dator och servern som ett öppet vykort. Alla på vägen kan läsa det.", icon: "Globe" },
      { id: "ht2", label: "HTTPS — krypterad", description: "HTTPS lägger till kryptering (SSL/TLS). Data skickas i ett förseglat kuvert som bara du och servern kan öppna.", icon: "Lock" },
      { id: "ht3", label: "Hänglåset", description: "Det lilla hänglåset i webbläsaren visar att sidan använder HTTPS. Saknas det? Fyll aldrig i lösenord eller personuppgifter.", icon: "ShieldCheck" },
      { id: "ht4", label: "Varför det spelar roll", description: "Vid inloggning, bankärenden och jobbsystem skickas känslig data. HTTPS skyddar allt — lösenord, personnummer, allt.", icon: "KeyRound" },
    ],
  },
  {
    id: "vpn",
    title: "Vad är en VPN?",
    description: "En privat tunnel genom internet.",
    category: "it-grunderna",
    steps: [
      { id: "vpn1", label: "Utan VPN", description: "Din internettrafik går öppet från din dator till servern. Din internetleverantör och andra kan se vilka sidor du besöker.", icon: "Globe" },
      { id: "vpn2", label: "VPN-tunnel", description: "En VPN skapar en krypterad tunnel. All din trafik skickas genom tunneln — ingen utomstående kan se vad du gör.", icon: "Lock" },
      { id: "vpn3", label: "Kommunens VPN", description: "När du jobbar hemifrån och ansluter via VPN ser det ut som att du sitter på kontoret. Du kan nå interna system säkert.", icon: "Building2" },
      { id: "vpn4", label: "Skyddar på öppna nätverk", description: "På caféets Wi-Fi kan VPN skydda dig. Utan VPN kan någon på samma nätverk potentiellt avlyssna din trafik.", icon: "Shield" },
    ],
  },
  {
    id: "cookies",
    title: "Vad är cookies?",
    description: "Små textfiler som webbsidor sparar på din dator.",
    category: "it-grunderna",
    steps: [
      { id: "coo1", label: "Du besöker en sida", description: "När du besöker en webbsida sparar den en liten textfil (cookie) på din dator. Som ett namnlapp som säger 'den här personen har varit här'.", icon: "FileText" },
      { id: "coo2", label: "Nödvändiga cookies", description: "Vissa cookies behövs för att sidan ska fungera — t.ex. att hålla dig inloggad eller komma ihåg din kundvagn.", icon: "ShieldCheck" },
      { id: "coo3", label: "Spårningscookies", description: "Andra cookies följer dig mellan webbsidor för att visa riktade annonser. Det är dessa du kan tacka nej till.", icon: "Eye" },
      { id: "coo4", label: "Cookiebanners", description: "GDPR kräver att webbsidor frågar om lov. Därför ser du 'Acceptera cookies'-rutan. Du kan välja vilka du godkänner.", icon: "Shield" },
    ],
  },
  {
    id: "cache",
    title: "Vad är cache?",
    description: "Snabbminnet som gör allt snabbare.",
    category: "it-grunderna",
    steps: [
      { id: "cac1", label: "Utan cache", description: "Varje gång du besöker en sida laddas allt ner på nytt — bilder, stilmallar, skript. Långsamt.", icon: "Clock" },
      { id: "cac2", label: "Med cache", description: "Webbläsaren sparar en kopia av filerna lokalt. Nästa gång du besöker sidan hämtas de från din dator — mycket snabbare.", icon: "Zap" },
      { id: "cac3", label: "Cache finns överallt", description: "Inte bara webbläsaren — din dators processor, appar och servrar använder cache. Principen: spara det vanligaste nära.", icon: "Layers" },
      { id: "cac4", label: "Rensa cache", description: "Ibland visar webbläsaren en gammal version av en sida. Då hjälper det att rensa cache — webbläsaren hämtar allt på nytt.", icon: "RefreshCw" },
    ],
  },
  {
    id: "brandvagg",
    title: "Vad är en brandvägg?",
    description: "Vakten som bestämmer vem som får passera.",
    category: "it-grunderna",
    steps: [
      { id: "bv1", label: "Trafik in och ut", description: "All data som skickas till och från ditt nätverk passerar genom brandväggen — som en vakt vid en dörr.", icon: "Shield" },
      { id: "bv2", label: "Regler", description: "Brandväggen har regler: 'Webbtrafik får passera. Okänd trafik från utlandet blockeras.' Den filtrerar baserat på regler.", icon: "Filter" },
      { id: "bv3", label: "Skyddar nätverket", description: "Hackare som försöker nå kommunens servrar stoppas. Virus som försöker ringa hem blockeras.", icon: "ShieldCheck" },
      { id: "bv4", label: "Finns i flera lager", description: "Windows har en inbyggd brandvägg på din dator. Kommunen har dessutom en nätverksbrandvägg som skyddar hela organisationen.", icon: "Layers" },
    ],
  },
  {
    id: "ip-adress",
    title: "Vad är en IP-adress?",
    description: "Varje enhet på internet har ett unikt nummer.",
    category: "it-grunderna",
    steps: [
      { id: "ip1", label: "Som en postadress", description: "Precis som ditt hem har en gatuadress har varje dator, telefon och server på internet en IP-adress — t.ex. 192.168.1.42.", icon: "MapPin" },
      { id: "ip2", label: "Hitta rätt mottagare", description: "När du besöker en webbsida används IP-adressen för att hitta rätt server och skicka tillbaka svaret till just din dator.", icon: "Send" },
      { id: "ip3", label: "Intern vs. extern", description: "Din dator har en intern IP (inom kontoret) och delar en extern IP (ut mot internet) med hela nätverket.", icon: "Network" },
      { id: "ip4", label: "IPv4 och IPv6", description: "Gamla formatet (IPv4) har 'bara' 4 miljarder adresser — det räcker inte längre. IPv6 har i princip oändligt många.", icon: "ArrowUpRight" },
    ],
  },
  {
    id: "saas",
    title: "Vad är SaaS?",
    description: "Program som tjänst — hyra istället för köpa.",
    category: "it-grunderna",
    steps: [
      { id: "sas1", label: "Förr: Installera program", description: "Du köpte en CD, installerade programmet på din dator. Uppdateringar var krångliga. En dator = en licens.", icon: "HardDrive" },
      { id: "sas2", label: "Nu: SaaS", description: "Software as a Service — programmet körs i molnet. Du öppnar det i webbläsaren. Inga installationer.", icon: "Cloud" },
      { id: "sas3", label: "Alltid uppdaterat", description: "Leverantören sköter uppdateringar, säkerhet och backup. Du får alltid senaste versionen automatiskt.", icon: "RefreshCw" },
      { id: "sas4", label: "Exempel du redan använder", description: "Microsoft 365, Google Workspace, Intric, Teams — alla är SaaS. Du prenumererar istället för att köpa.", icon: "CreditCard" },
    ],
  },

  // --- NYA AI-GRUNDERNA ---
  {
    id: "ai-modell",
    title: "Vad är en AI-modell?",
    description: "Det färdigtränade 'programmet' som kan svara.",
    category: "ai-grunderna",
    steps: [
      { id: "aim1", label: "Träning", description: "En AI-modell skapas genom att mata en algoritm med enorma mängder data. Under veckor lär den sig mönster.", icon: "Cpu" },
      { id: "aim2", label: "Modellen sparas", description: "Resultatet av träningen är en modell — en fil med miljarder inlärda parametrar (siffror). T.ex. GPT-4, Claude, Llama.", icon: "Box" },
      { id: "aim3", label: "Du skickar input", description: "Du skriver en fråga. Modellen bearbetar den genom alla sina inlärda mönster.", icon: "MessageSquare" },
      { id: "aim4", label: "Modellen ger output", description: "Baserat på mönstren genererar modellen ett svar — ord för ord. Den 'vet' inte saker, den förutsäger vad som borde komma härnäst.", icon: "Sparkles" },
    ],
  },
  {
    id: "traningsdata",
    title: "Vad är träningsdata?",
    description: "AI:ns skolmaterial — det den lär sig från.",
    category: "ai-grunderna",
    steps: [
      { id: "td1", label: "Data samlas in", description: "Böcker, webbsidor, artiklar, kod — miljarder texter samlas ihop som träningsunderlag.", icon: "FileStack" },
      { id: "td2", label: "Data rensas", description: "Duplicat, skräp och olämpligt innehåll filtreras bort. Kvaliteten på datan avgör kvaliteten på AI:n.", icon: "Filter" },
      { id: "td3", label: "AI:n studerar", description: "Modellen läser igenom all data och hittar mönster — hur språk fungerar, fakta, samband.", icon: "BookOpen" },
      { id: "td4", label: "Kunskap har ett datum", description: "AI:n vet bara det som fanns i träningsdatan. Ny information efter träningen känner den inte till — därav 'kunskapsavskärning'.", icon: "Calendar" },
    ],
  },
  {
    id: "algoritm",
    title: "Vad är en algoritm?",
    description: "Ett recept som datorn följer steg för steg.",
    category: "ai-grunderna",
    steps: [
      { id: "alg1", label: "Ett recept", description: "En algoritm är en uppsättning steg-för-steg-instruktioner för att lösa ett problem — som ett matrecept.", icon: "ListOrdered" },
      { id: "alg2", label: "Vardagsexempel", description: "'Ta det billigaste alternativet' — det är en algoritm. 'Sortera mejl efter datum' — också en algoritm.", icon: "ArrowUpDown" },
      { id: "alg3", label: "I AI", description: "En maskininlärningsalgoritm är receptet för HUR en AI ska lära sig från data. Den bestämmer inlärningsmetoden.", icon: "Brain" },
      { id: "alg4", label: "Resultat: En modell", description: "Algoritmen + träningsdata = en färdig modell. Algoritmen är receptet, datan är ingredienserna, modellen är den färdiga rätten.", icon: "ChefHat" },
    ],
  },
  {
    id: "overvakad-inlarning",
    title: "Övervakad inlärning",
    description: "AI lär sig med facit i hand.",
    category: "ai-grunderna",
    steps: [
      { id: "oi1", label: "Data med facit", description: "AI:n får exempel med rätt svar: 'Den här bilden = katt. Den här bilden = hund.' Tusentals sådana par.", icon: "Tag" },
      { id: "oi2", label: "AI:n gissar", description: "Modellen tittar på en ny bild och gissar: 'Katt?' Den jämför sitt svar med facit.", icon: "Eye" },
      { id: "oi3", label: "Justering", description: "Fel svar? Modellen justerar sina parametrar lite grann. Rätt svar? Bra, behåll inställningarna. Miljontals gånger.", icon: "SlidersHorizontal" },
      { id: "oi4", label: "Fungerar på nya data", description: "Efter träning kan AI:n klassificera bilder den aldrig sett förut. Används för e-postfilter, bildigenkänning och diagnosstöd.", icon: "Sparkles" },
    ],
  },
  {
    id: "oovervakad-inlarning",
    title: "Oövervakad inlärning",
    description: "AI hittar mönster utan facit.",
    category: "ai-grunderna",
    steps: [
      { id: "ooi1", label: "Data utan facit", description: "AI:n får data utan etiketter — bara rådata. Ingen säger 'det här är en katt'. AI:n måste hitta mönster själv.", icon: "Puzzle" },
      { id: "ooi2", label: "Gruppering (klustring)", description: "AI:n sorterar liknande saker i grupper: 'De här bilderna liknar varandra, de här också.' Utan att veta att det är katter och hundar.", icon: "LayoutGrid" },
      { id: "ooi3", label: "Mönster upptäcks", description: "AI:n hittar strukturer i data som människor kan missa — t.ex. grupper av invånare med liknande behov.", icon: "TrendingUp" },
      { id: "ooi4", label: "Användning", description: "Kundgruppering, anomalidetektering (hitta avvikelser), rekommendationer. Bra när du inte vet vad du letar efter.", icon: "Search" },
    ],
  },
  {
    id: "forstarkningsinlarning",
    title: "Förstärkningsinlärning",
    description: "AI lär sig genom att prova och få belöning.",
    category: "ai-grunderna",
    steps: [
      { id: "fi1", label: "En agent i en miljö", description: "Tänk dig en AI som spelar ett spel. Den kan göra olika val och ser vad som händer.", icon: "Gamepad2" },
      { id: "fi2", label: "Belöning och straff", description: "Bra val ger poäng (belöning). Dåliga val ger minuspoäng (straff). AI:n vill maximera sina poäng.", icon: "Trophy" },
      { id: "fi3", label: "Prova och lära", description: "AI:n provar miljontals gånger, lär sig vilka strategier som ger mest belöning. Trial and error i hög hastighet.", icon: "RotateCcw" },
      { id: "fi4", label: "RLHF i ChatGPT/Claude", description: "Språkmodeller finjusteras med förstärkningsinlärning. Mänskliga bedömare poängsätter svar — AI:n lär sig ge bättre svar.", icon: "ThumbsUp" },
    ],
  },
  {
    id: "datorseende",
    title: "Vad är datorseende?",
    description: "Hur AI kan 'se' och förstå bilder.",
    category: "ai-grunderna",
    steps: [
      { id: "ds1", label: "Bild = pixlar", description: "En bild är bara en matris av siffror (pixlar). Varje pixel har ett färgvärde. AI:n 'ser' bara siffror.", icon: "Image" },
      { id: "ds2", label: "Mönster hittas", description: "Ett neuralt nätverk lär sig hitta kanter, former och sedan hela objekt — stegvis mer avancerade mönster.", icon: "Eye" },
      { id: "ds3", label: "Igenkänning", description: "AI:n kan identifiera: 'Det här är en bil', 'Det här är en person', 'Det här är ett trafikljus'. Med hög precision.", icon: "ScanEye" },
      { id: "ds4", label: "Användning", description: "Ansiktsigenkänning, självkörande bilar, medicinsk bildanalys, OCR (läsa text i bilder). Används i kommunens dokumentskanning.", icon: "Camera" },
    ],
  },
  {
    id: "nlp",
    title: "Vad är NLP?",
    description: "Natural Language Processing — AI som förstår text.",
    category: "ai-grunderna",
    steps: [
      { id: "nlp1", label: "Naturligt språk", description: "Människor skriver och pratar med vardagsspråk — med slang, kontext och nyanser. Det är svårt för datorer.", icon: "MessageSquare" },
      { id: "nlp2", label: "NLP = språktolkning", description: "Natural Language Processing är AI-fältet som lär datorer förstå, tolka och generera mänskligt språk.", icon: "Brain" },
      { id: "nlp3", label: "Uppgifter NLP löser", description: "Översättning, sammanfattning, sentimentanalys ('är mejlet argt?'), textklassificering, chatbotar — allt är NLP.", icon: "ListChecks" },
      { id: "nlp4", label: "LLM:er är NLP", description: "ChatGPT, Claude och Intric är avancerad NLP. De förstår kontext, svarar på frågor och skriver text — tack vare NLP-forskning.", icon: "Sparkles" },
    ],
  },

  // --- NYA SPRÅKMODELLER ---
  {
    id: "llm",
    title: "Vad är en LLM?",
    description: "Large Language Model — en jättestor språkmaskin.",
    category: "sprakmodeller",
    steps: [
      { id: "llm1", label: "Large Language Model", description: "LLM står för Large Language Model — en AI-modell med miljarder parametrar, tränad på enorma mängder text.", icon: "BookText" },
      { id: "llm2", label: "Hur den lärde sig", description: "LLM:en läste miljarder webbsidor, böcker och artiklar. Den lärde sig mönster: 'efter detta ord kommer troligen detta'.", icon: "BookOpen" },
      { id: "llm3", label: "Vad den kan", description: "Skriva, sammanfatta, översätta, koda, analysera — allt som handlar om text. Den genererar ord baserat på sannolikhet.", icon: "Sparkles" },
      { id: "llm4", label: "Exempel", description: "GPT-4, Claude, Gemini, Llama — alla är LLM:er. De skiljer sig i storlek, träningsdata och finjustering.", icon: "Layers" },
    ],
  },
  {
    id: "gpt",
    title: "Vad är GPT?",
    description: "Generative Pre-trained Transformer — OpenAI:s modellserie.",
    category: "sprakmodeller",
    steps: [
      { id: "gpt1", label: "G = Generative", description: "Modellen GENERERAR text — den skapar nytt innehåll ord för ord, baserat på sannolikheter.", icon: "Sparkles" },
      { id: "gpt2", label: "P = Pre-trained", description: "Modellen är FÖR-TRÄNAD på enorma mängder text innan du använder den. Grundkunskapen finns redan.", icon: "BookOpen" },
      { id: "gpt3", label: "T = Transformer", description: "Transformer är arkitekturen — typen av neuralt nätverk. Det är 'motorn' som gör GPT så bra på språk.", icon: "Cpu" },
      { id: "gpt4", label: "GPT-3.5, GPT-4, GPT-4o", description: "Varje version är bättre. GPT-4 har fler parametrar och mer träningsdata. GPT-4o är snabbare och kan hantera bild/ljud.", icon: "TrendingUp" },
    ],
  },
  {
    id: "transformer",
    title: "Vad är en Transformer?",
    description: "Arkitekturen bakom alla moderna språkmodeller.",
    category: "sprakmodeller",
    steps: [
      { id: "tf1", label: "Problemet innan", description: "Äldre modeller läste text ord för ord, i ordning. Långsamt och de 'glömde' tidiga delar av långa texter.", icon: "ArrowRight" },
      { id: "tf2", label: "Attention-mekanismen", description: "Transformern kan titta på ALLA ord samtidigt och avgöra vilka som hör ihop. 'Banken' — menar vi pengar eller flod? Kontexten avgör.", icon: "Focus" },
      { id: "tf3", label: "Parallell bearbetning", description: "Istället för ord-för-ord bearbetar transformern hela meningen parallellt. Mycket snabbare, speciellt med GPU:er.", icon: "Zap" },
      { id: "tf4", label: "Grunden för allt", description: "GPT, Claude, Gemini, BERT — alla bygger på transformer-arkitekturen. Uppfanns 2017 av Google och revolutionerade AI.", icon: "Landmark" },
    ],
  },
  {
    id: "attention",
    title: "Vad är Attention?",
    description: "Hur AI:n förstår vilka ord som hör ihop.",
    category: "sprakmodeller",
    steps: [
      { id: "att1", label: "Alla ord vägs", description: "När AI:n läser en mening räknar den ut hur mycket varje ord ska 'uppmärksamma' alla andra ord.", icon: "Focus" },
      { id: "att2", label: "Kopplingar skapas", description: "'Katten satt på mattan och den spann.' — Attention kopplar 'den' till 'katten', inte till 'mattan'. Samband förstås.", icon: "Link2" },
      { id: "att3", label: "Self-Attention", description: "Varje ord i meningen tittar på alla andra ord och bestämmer vilka som är relevanta. Det sker i varje lager av modellen.", icon: "Network" },
      { id: "att4", label: "Nyckeln till förståelse", description: "Attention är det som gör att LLM:er förstår kontext och sammanhang. Utan attention skulle AI:n bara se isolerade ord.", icon: "Brain" },
    ],
  },
  {
    id: "generativ-ai",
    title: "Vad är generativ AI?",
    description: "AI som skapar nytt innehåll.",
    category: "sprakmodeller",
    steps: [
      { id: "gen1", label: "Analytisk AI", description: "Traditionell AI analyserar: 'Denna bild innehåller en katt.' Den sorterar och klassificerar befintliga saker.", icon: "Search" },
      { id: "gen2", label: "Generativ AI", description: "Generativ AI SKAPAR: 'Här är en ny bild av en katt som rider på en enhörning.' Den producerar nytt innehåll.", icon: "Sparkles" },
      { id: "gen3", label: "Vad den kan skapa", description: "Text (ChatGPT, Claude), bilder (DALL-E, Midjourney), kod, musik, video — allt som kan genereras token för token.", icon: "Palette" },
      { id: "gen4", label: "I kommunen", description: "Skriva utkast till beslut, sammanfatta protokoll, generera informationsmaterial — generativ AI hjälper med skapande arbete.", icon: "PenTool" },
    ],
  },
  {
    id: "top-p",
    title: "Vad är Top-p (Nucleus Sampling)?",
    description: "En annan ratt som styr AI:ns ordval.",
    category: "sprakmodeller",
    steps: [
      { id: "tp1", label: "AI:n rankar ord", description: "För varje position rankar AI:n alla möjliga nästa ord efter sannolikhet. 'Stockholm' 40%, 'Göteborg' 25%, 'Malmö' 15%...", icon: "ListOrdered" },
      { id: "tp2", label: "Top-p filtrerar", description: "Top-p = 0.9 betyder: välj bland de mest sannolika orden som tillsammans utgör 90% sannolikhet. Resten ignoreras.", icon: "Filter" },
      { id: "tp3", label: "Låg Top-p = fokuserat", description: "Top-p = 0.1 — bara de allra mest sannolika orden. Förutsägbart och repetitivt. Bra för fakta.", icon: "Target" },
      { id: "tp4", label: "Hög Top-p = varierat", description: "Top-p = 0.95 — fler ord får vara med. Mer variation och kreativitet, men ibland oväntat. Bra för fri text.", icon: "Sparkles" },
    ],
  },
  {
    id: "systemprompt",
    title: "Vad är en systemprompt?",
    description: "De dolda instruktionerna som styr AI:ns beteende.",
    category: "sprakmodeller",
    steps: [
      { id: "sp1", label: "Du ser den inte", description: "Bakom varje AI-assistent finns en systemprompt — en dold instruktion som bestämmer hur AI:n ska bete sig.", icon: "Eye" },
      { id: "sp2", label: "Den sätter regler", description: "'Du är en hjälpsam assistent för Katrineholms kommun. Svara på svenska. Hänvisa till interna dokument.' — AI:n följer dessa regler.", icon: "ScrollText" },
      { id: "sp3", label: "Personlighet och gränser", description: "Systemprompten bestämmer ton (formell/vänlig), vad AI:n får och inte får svara på, och vilken roll den spelar.", icon: "UserCog" },
      { id: "sp4", label: "I Intric", description: "Varje assistent i Intric har en egen systemprompt. Det är det som skiljer HR-assistenten från IT-assistenten — samma modell, olika instruktioner.", icon: "Settings" },
    ],
  },
  {
    id: "multimodal-ai",
    title: "Vad är multimodal AI?",
    description: "AI som förstår text, bild, ljud och video.",
    category: "sprakmodeller",
    steps: [
      { id: "mm1", label: "En modalitet = en typ", description: "Text är en modalitet. Bild en annan. Ljud en tredje. Traditionella modeller hanterar bara en i taget.", icon: "FileText" },
      { id: "mm2", label: "Multimodal = flera", description: "En multimodal AI kan hantera text OCH bild OCH ljud i samma konversation. Du kan skicka en bild och fråga om den.", icon: "Layers" },
      { id: "mm3", label: "Exempel", description: "Fota en felkod på skärmen → AI:n läser bilden och förklarar felet. Ladda upp ett diagram → AI:n analyserar trenden.", icon: "Camera" },
      { id: "mm4", label: "GPT-4o, Claude, Gemini", description: "Moderna modeller är multimodala. GPT-4o hanterar text, bild och ljud. Gemini kan även hantera video.", icon: "Sparkles" },
    ],
  },
  {
    id: "grundmodell",
    title: "Vad är en grundmodell?",
    description: "Basen som alla specialiserade AI:er byggs på.",
    category: "sprakmodeller",
    steps: [
      { id: "gm1", label: "Dyr att bygga", description: "En grundmodell (foundation model) tränas på enorma datamängder med enorm beräkningskraft. Kostar miljontals kronor.", icon: "Server" },
      { id: "gm2", label: "Generell kunskap", description: "Resultatet: en modell med bred kunskap om språk, världen och logik. GPT-4, Claude, Llama är alla grundmodeller.", icon: "Globe" },
      { id: "gm3", label: "Specialisering", description: "Grundmodellen kan sedan finjusteras för specifika uppgifter — medicinsk AI, juridisk AI, kodningsassistent.", icon: "Wrench" },
      { id: "gm4", label: "Jämförelse", description: "Tänk: grundmodell = utbildad generalist. Finjustering = specialistutbildning. Du bygger vidare på basen.", icon: "GraduationCap" },
    ],
  },
  {
    id: "parametrar",
    title: "Vad är parametrar i en AI-modell?",
    description: "De miljarder 'rattarna' som gör AI:n smart.",
    category: "sprakmodeller",
    steps: [
      { id: "par1", label: "Siffror i modellen", description: "Parametrar är siffror (vikter) inuti modellen. GPT-4 har uppskattningsvis 1,8 biljoner parametrar. Claude har liknande skala.", icon: "Binary" },
      { id: "par2", label: "Justeras under träning", description: "Under träning justeras varje parameter lite grann, miljontals gånger, tills modellen ger bra svar.", icon: "SlidersHorizontal" },
      { id: "par3", label: "Fler parametrar = smartare?", description: "Generellt ja, men inte alltid. En modell med 70 miljarder parametrar och bra data kan slå en med 175 miljarder och sämre data.", icon: "TrendingUp" },
      { id: "par4", label: "Storlek kostar", description: "Fler parametrar = mer beräkningskraft behövs = dyrare att köra. Därför finns små, snabba modeller och stora, kraftfulla.", icon: "Scale" },
    ],
  },
  {
    id: "hallucination",
    title: "Vad är en hallucination?",
    description: "När AI:n hittar på saker som låter rätt men är fel.",
    category: "sprakmodeller",
    steps: [
      { id: "hal1", label: "AI:n låter säker", description: "Du frågar om en lag. AI:n svarar med exakt paragrafnummer, detaljerad förklaring — och det hela låter perfekt.", icon: "MessageSquare" },
      { id: "hal2", label: "Men det stämmer inte", description: "Problemet: lagen finns inte. AI:n 'hittade på' ett troligt svar baserat på mönster — inte på fakta. Det kallas hallucination.", icon: "AlertTriangle" },
      { id: "hal3", label: "Varför det händer", description: "AI:n förutsäger mest sannolika nästa ord — den 'vet' inte vad som är sant. Om mönstret ser rätt ut, genererar den det.", icon: "Brain" },
      { id: "hal4", label: "Hur du skyddar dig", description: "Verifiera viktig information. Använd RAG (Intric) för att förankra svar i dokument. Låt AI:n citera källor.", icon: "ShieldCheck" },
    ],
  },
  {
    id: "grounding",
    title: "Vad är grounding?",
    description: "Att förankra AI:ns svar i verklig information.",
    category: "sprakmodeller",
    steps: [
      { id: "gro1", label: "Utan grounding", description: "AI:n svarar enbart från sin träningsdata. Risk: hallucination, föråldrad info, generella svar.", icon: "Cloud" },
      { id: "gro2", label: "Med grounding", description: "AI:n får tillgång till aktuella, verifierade dokument och söker i dem innan den svarar.", icon: "Anchor" },
      { id: "gro3", label: "RAG = grounding", description: "Retrieval-Augmented Generation (RAG) är den vanligaste grounding-tekniken. Intric använder RAG för att förankra svar i era dokument.", icon: "Search" },
      { id: "gro4", label: "Resultat", description: "Förankrade svar med källhänvisningar. Mindre hallucination, mer pålitligt. AI:n svarar baserat på fakta, inte gissningar.", icon: "Check" },
    ],
  },
];

export const EXPLAINERS: AnimatedExplainer[] = [
  ...EXPLAINERS_1,
  ...EXPLAINERS_2,
  ...EXPLAINERS_3,
];