import type { AnimatedExplainer } from "./knowledge-bank";

export const EXPLAINERS_2: AnimatedExplainer[] = [
  // ===========================================================================
  // AI PÅ JOBBET
  // ===========================================================================
  {
    id: "chatbot",
    title: "Chatbot",
    description: "En AI som svarar på frågor i en chattkonversation.",
    category: "ai-pa-jobbet",
    steps: [
      { id: "cb1", label: "Användaren skriver", description: "Du skriver en fråga i chattrutan, precis som du skulle skriva till en kollega. Till exempel: 'Hur ansöker jag om semester?'", icon: "MessageSquare" },
      { id: "cb2", label: "AI:n tolkar frågan", description: "Chatboten analyserar din text och försöker förstå vad du menar. Den bryter ner frågan i nyckelord och sammanhang.", icon: "Brain" },
      { id: "cb3", label: "Svar genereras", description: "Baserat på sin träningsdata eller kopplad kunskap formulerar AI:n ett svar som matchar din fråga.", icon: "Sparkles" },
      { id: "cb4", label: "Du får svar direkt", description: "Svaret visas i chatten inom sekunder. Du kan ställa följdfrågor för att fördjupa eller förtydliga.", icon: "MessagesSquare" },
    ],
  },
  {
    id: "copilot-begrepp",
    title: "Copilot-begreppet",
    description: "En AI-assistent som jobbar vid din sida — inte istället för dig.",
    category: "ai-pa-jobbet",
    steps: [
      { id: "cp1", label: "Du arbetar som vanligt", description: "Du sitter i Word, Excel eller ett annat verktyg och jobbar med dina uppgifter precis som vanligt.", icon: "Monitor" },
      { id: "cp2", label: "AI:n observerar", description: "Copiloten ser vad du arbetar med och förstår sammanhanget — vilken typ av dokument, vilka data, vad du försöker åstadkomma.", icon: "Eye" },
      { id: "cp3", label: "Förslag dyker upp", description: "AI:n ger dig förslag: en mening att fortsätta med, en formel, eller ett utkast. Du väljer om du vill använda det.", icon: "Lightbulb" },
      { id: "cp4", label: "Du behåller kontrollen", description: "Du godkänner, ändrar eller avvisar förslagen. Copiloten är en assistent — du fattar alltid det slutgiltiga beslutet.", icon: "UserCheck" },
    ],
  },
  {
    id: "automatisering",
    title: "Automatisering med AI",
    description: "Låt AI:n sköta repetitiva uppgifter åt dig.",
    category: "ai-pa-jobbet",
    steps: [
      { id: "au1", label: "Identifiera repetitivt arbete", description: "Först identifierar du uppgifter som görs på samma sätt varje gång — till exempel att sortera inkommande e-post eller fylla i formulär.", icon: "Repeat" },
      { id: "au2", label: "Skapa en regel", description: "Du sätter upp en automatisering: 'När X händer, gör Y.' Till exempel: 'När ett ärende kommer in, kategorisera det och skicka vidare.'", icon: "Settings" },
      { id: "au3", label: "AI:n utför arbetet", description: "AI:n kör uppgiften automatiskt varje gång den triggas. Den följer dina regler men kan hantera variationer.", icon: "Bot" },
      { id: "au4", label: "Du övervakar", description: "Du kontrollerar att automatiseringen fungerar som tänkt. Vid oklara fall flaggar AI:n för manuell hantering.", icon: "ShieldCheck" },
    ],
  },
  {
    id: "sammanfattning",
    title: "AI-sammanfattning",
    description: "Få långa texter sammanfattade på sekunder.",
    category: "ai-pa-jobbet",
    steps: [
      { id: "sm1", label: "Lång text in", description: "Du har ett långt dokument, en rapport eller ett protokoll. Det kan vara tiotals sidor som du behöver få grepp om.", icon: "FileText" },
      { id: "sm2", label: "AI:n läser allt", description: "AI:n läser igenom hela texten och identifierar de viktigaste punkterna, besluten och slutsatserna.", icon: "ScanText" },
      { id: "sm3", label: "Sammanfattning skapas", description: "Du får en kort, strukturerad sammanfattning med de viktigaste delarna. Ofta på bara några rader.", icon: "ListChecks" },
      { id: "sm4", label: "Spara tid", description: "Istället för att läsa i 30 minuter får du kärnan på en minut. Du kan alltid gå tillbaka till originalet vid behov.", icon: "Clock" },
    ],
  },
  {
    id: "textgenerering",
    title: "Textgenerering",
    description: "AI:n skriver utkast som du finslipar.",
    category: "ai-pa-jobbet",
    steps: [
      { id: "tg1", label: "Du ger instruktioner", description: "Du beskriver vad du vill ha skrivet: 'Skriv ett informationsbrev om nya öppettider till biblioteket, vänlig ton.'", icon: "Pencil" },
      { id: "tg2", label: "AI:n skapar utkast", description: "AI:n genererar en text baserat på dina instruktioner. Den följer ton, längd och format som du angett.", icon: "Sparkles" },
      { id: "tg3", label: "Du granskar och justerar", description: "Du läser igenom utkastet, ändrar formuleringar och lägger till detaljer som bara du känner till.", icon: "PenLine" },
      { id: "tg4", label: "Färdig text", description: "Resultatet är en professionell text som du skapat på en bråkdel av tiden. AI:n skrev utkastet — du säkrade kvaliteten.", icon: "FileCheck" },
    ],
  },
  {
    id: "motessammanfattning",
    title: "Mötessammanfattning med AI",
    description: "Från mötesinspelning till strukturerat protokoll automatiskt.",
    category: "ai-pa-jobbet",
    steps: [
      { id: "ms1", label: "Mötet spelas in", description: "Mötet hålls i Teams eller liknande och spelas in. Ljudet fångas upp under hela mötet.", icon: "Mic" },
      { id: "ms2", label: "Tal blir text", description: "AI:n transkriberar allt som sägs — varje deltagares inlägg omvandlas till text med talargenkänning.", icon: "FileAudio" },
      { id: "ms3", label: "Nyckelinnehåll identifieras", description: "AI:n plockar ut beslut, åtgärdspunkter och viktiga diskussioner ur den långa transkriberingen.", icon: "ListChecks" },
      { id: "ms4", label: "Protokoll skapas", description: "Du får ett strukturerat mötesprotokoll med beslut, ansvariga och nästa steg — klart att skicka ut.", icon: "ClipboardCheck" },
    ],
  },
  {
    id: "ai-beslutsfattande",
    title: "AI som beslutsstöd",
    description: "AI hjälper dig analysera — men du fattar beslutet.",
    category: "ai-pa-jobbet",
    steps: [
      { id: "ab1", label: "Data samlas in", description: "AI:n samlar och strukturerar relevant data: statistik, tidigare beslut, trender och andra underlag.", icon: "Database" },
      { id: "ab2", label: "Analys och mönster", description: "AI:n analyserar all data och hittar mönster, samband och avvikelser som kan vara svåra att se manuellt.", icon: "BarChart3" },
      { id: "ab3", label: "Rekommendation", description: "Baserat på analysen presenterar AI:n ett eller flera förslag med för- och nackdelar för varje alternativ.", icon: "Lightbulb" },
      { id: "ab4", label: "Människan beslutar", description: "Du väger AI:ns analys mot din erfarenhet, etik och lokalkännedom. Beslutet är alltid ditt — AI:n ger bara underlag.", icon: "UserCheck" },
    ],
  },
  {
    id: "arendehantering-ai",
    title: "AI i ärendehantering",
    description: "Snabbare sortering och handläggning av ärenden.",
    category: "ai-pa-jobbet",
    steps: [
      { id: "ah1", label: "Ärende kommer in", description: "En medborgare skickar in en ansökan, felanmälan eller fråga via e-post, formulär eller telefon.", icon: "Inbox" },
      { id: "ah2", label: "AI sorterar", description: "AI:n läser ärendet och kategoriserar det automatiskt: typ av ärende, prioritet och vilken avdelning som ska hantera det.", icon: "FolderOpen" },
      { id: "ah3", label: "Förslag på svar", description: "AI:n föreslår ett svar baserat på liknande ärenden. Vid standardärenden kan svaret vara nästan klart direkt.", icon: "MessageSquareReply" },
      { id: "ah4", label: "Handläggaren granskar", description: "Handläggaren kontrollerar AI:ns förslag, gör eventuella justeringar och skickar svaret. Komplexare ärenden hanteras helt manuellt.", icon: "UserCheck" },
    ],
  },
  {
    id: "bildgenerering",
    title: "Bildgenerering med AI",
    description: "Skapa bilder från textbeskrivningar.",
    category: "ai-pa-jobbet",
    steps: [
      { id: "bg1", label: "Du beskriver bilden", description: "Du skriver en textbeskrivning, en s.k. prompt: 'En solig dag vid Djulösjön med lekande barn.' Ju mer detaljer, desto bättre resultat.", icon: "Pencil" },
      { id: "bg2", label: "AI:n tolkar prompten", description: "AI:n bryter ner din text i koncept: miljö, ljus, färger, objekt. Den bygger en intern bild av vad du vill ha.", icon: "Brain" },
      { id: "bg3", label: "Bilden skapas", description: "Pixel för pixel genereras en helt ny bild. Den existerade inte innan — AI:n skapar den baserat på mönster den lärt sig.", icon: "Image" },
      { id: "bg4", label: "Du väljer och justerar", description: "Du får ofta flera förslag att välja mellan. Du kan be AI:n justera detaljer tills bilden passar ditt behov.", icon: "SlidersHorizontal" },
    ],
  },
  {
    id: "ocr",
    title: "OCR — textavläsning",
    description: "AI läser text från bilder och skannade dokument.",
    category: "ai-pa-jobbet",
    steps: [
      { id: "oc1", label: "Dokument skannas", description: "Ett pappersdokument skannas eller fotograferas. Datorn ser det som en bild — inte som text.", icon: "ScanLine" },
      { id: "oc2", label: "AI hittar texten", description: "OCR-tekniken analyserar bilden och identifierar var det finns bokstäver, siffror och ord.", icon: "Eye" },
      { id: "oc3", label: "Text extraheras", description: "Varje tecken omvandlas från bild till digital text. AI:n hanterar även dålig kvalitet och handstil.", icon: "FileOutput" },
      { id: "oc4", label: "Redigerbar text", description: "Nu har du sökbar, kopierbar och redigerbar text. Du kan lägga in den i system, söka i arkiv eller bearbeta vidare.", icon: "FileText" },
    ],
  },
  {
    id: "sentimentanalys",
    title: "Sentimentanalys",
    description: "AI läser av känslan och tonen i text.",
    category: "ai-pa-jobbet",
    steps: [
      { id: "sa1", label: "Text matas in", description: "Du matar in text — till exempel medborgarenkäter, e-post eller sociala medier-inlägg om kommunens tjänster.", icon: "FileText" },
      { id: "sa2", label: "AI analyserar tonen", description: "AI:n läser texten och bedömer om den är positiv, negativ eller neutral. Den fångar nyanser och känslor.", icon: "Brain" },
      { id: "sa3", label: "Resultat kategoriseras", description: "Texterna sorteras: 'Nöjd med ny lekplats' → Positiv. 'Väntetiden är för lång' → Negativ. Du ser trender.", icon: "BarChart3" },
      { id: "sa4", label: "Insikter för beslut", description: "Du får en överblick av hur medborgarna upplever tjänster och kan rikta förbättringsarbete dit det behövs mest.", icon: "TrendingUp" },
    ],
  },

  // ===========================================================================
  // INTRIC-PLATTFORMEN
  // ===========================================================================
  {
    id: "intric-plattform",
    title: "Intric-plattformen",
    description: "En svensk AI-plattform byggd för offentlig sektor.",
    category: "intric",
    steps: [
      { id: "ip1", label: "Svensk molnplattform", description: "Intric är en svensk AI-plattform som körs i säkra svenska datacenter. Data stannar i Sverige, vilket uppfyller kommunens krav.", icon: "Cloud" },
      { id: "ip2", label: "Koppla AI-modeller", description: "I Intric kan du koppla in olika AI-modeller (GPT, Claude, m.fl.) och använda dem genom ett gemensamt gränssnitt.", icon: "Plug" },
      { id: "ip3", label: "Ladda upp kunskap", description: "Du laddar upp dokument, riktlinjer och policyer. AI:n använder dessa som kunskapskälla när den svarar.", icon: "Upload" },
      { id: "ip4", label: "Bygg egna assistenter", description: "Du skapar skräddarsydda AI-assistenter för specifika arbetsuppgifter — utan att behöva kunna programmera.", icon: "Bot" },
      { id: "ip5", label: "Säker för kommunen", description: "All data skyddas med kryptering och åtkomstkontroll. Plattformen är designad för att uppfylla GDPR och offentlig sektors krav.", icon: "ShieldCheck" },
    ],
  },
  {
    id: "intric-space",
    title: "Intric Space",
    description: "En delad arbetsyta i Intric där ditt team samarbetar med AI.",
    category: "intric",
    steps: [
      { id: "is1", label: "Skapa ett Space", description: "Ett Space är som en gemensam arbetsyta i Intric. Du skapar ett Space för ditt team, din avdelning eller ett projekt.", icon: "LayoutGrid" },
      { id: "is2", label: "Bjud in medlemmar", description: "Du bjuder in kollegor till ditt Space. Alla medlemmar delar samma assistenter, kunskap och inställningar.", icon: "Users" },
      { id: "is3", label: "Dela resurser", description: "Allt ni bygger i Space:t — assistenter, kunskapssamlingar, konversationer — delas automatiskt med teamet.", icon: "Share2" },
      { id: "is4", label: "Håll ordning", description: "Varje Space är isolerat. Data och assistenter i ett Space syns inte i andra Spaces om du inte väljer att dela dem.", icon: "FolderLock" },
    ],
  },
  {
    id: "intric-assistent",
    title: "Intric-assistent",
    description: "En skräddarsydd AI-assistent i Intric för specifika uppgifter.",
    category: "intric",
    steps: [
      { id: "ia1", label: "Välj AI-modell", description: "Först väljer du vilken AI-modell assistenten ska använda — till exempel GPT-4 eller Claude — beroende på uppgift och säkerhetsklass.", icon: "Cpu" },
      { id: "ia2", label: "Skriv instruktioner", description: "Du ger assistenten en systemprompt: 'Du är en HR-assistent som svarar på frågor om tjänstledighet.' Detta styr hur den beter sig.", icon: "FileEdit" },
      { id: "ia3", label: "Koppla kunskap", description: "Du kopplar kunskapssamlingar till assistenten — t.ex. HR-policyer. Nu kan den svara baserat på era egna dokument.", icon: "Link" },
      { id: "ia4", label: "Testa och justera", description: "Du chattar med assistenten, testar olika frågor och finjusterar instruktionerna tills den svarar som du vill.", icon: "TestTube" },
      { id: "ia5", label: "Publicera", description: "Assistenten görs tillgänglig för ditt team i ert Space, eller delas via Intric Marketplace till hela organisationen.", icon: "Rocket" },
    ],
  },
  {
    id: "intric-kunskap",
    title: "Kunskap i Intric",
    description: "Så använder Intric dina dokument som AI-kunskapskälla.",
    category: "intric",
    steps: [
      { id: "ik1", label: "Ladda upp dokument", description: "Du laddar upp filer — PDF:er, Word-dokument, riktlinjer — till en kunskapssamling i Intric.", icon: "Upload" },
      { id: "ik2", label: "Text bryts ner", description: "Intric delar upp dokumenten i mindre textbitar (chunks) så att AI:n kan söka effektivt i innehållet.", icon: "Scissors" },
      { id: "ik3", label: "Vektorer skapas", description: "Varje textbit omvandlas till en vektor — en matematisk representation som fångar textens betydelse, inte bara orden.", icon: "Binary" },
      { id: "ik4", label: "Sökning vid fråga", description: "När du ställer en fråga söker Intric bland vektorerna och hittar de mest relevanta textbitarna från dina dokument.", icon: "Search" },
      { id: "ik5", label: "Svar med källa", description: "AI:n formulerar ett svar baserat på de hittade texterna och visar vilka dokument svaret kommer från.", icon: "BookOpen" },
    ],
  },
  {
    id: "intric-samling",
    title: "Kunskapssamlingar i Intric",
    description: "Organisera dina dokument i tematiska samlingar.",
    category: "intric",
    steps: [
      { id: "il1", label: "Skapa en samling", description: "Du skapar en kunskapssamling i Intric — t.ex. 'HR-policyer', 'Bygglovsregler' eller 'IT-riktlinjer'.", icon: "FolderPlus" },
      { id: "il2", label: "Ladda upp filer", description: "Du laddar upp relevanta dokument till samlingen. Intric stödjer PDF, Word, text och andra vanliga format.", icon: "Upload" },
      { id: "il3", label: "Automatisk indexering", description: "Intric bearbetar filerna automatiskt — bryter ner, indexerar och gör innehållet sökbart för AI:n.", icon: "RefreshCw" },
      { id: "il4", label: "Koppla till assistent", description: "Du kopplar samlingen till en eller flera assistenter. Nu kan de svara på frågor baserat på just dessa dokument.", icon: "Link" },
    ],
  },
  {
    id: "sakerhetsklasser",
    title: "Säkerhetsklasser i Intric",
    description: "Olika nivåer styr vilken data som får hanteras.",
    category: "intric",
    steps: [
      { id: "sk1", label: "Varför klasser?", description: "Offentlig sektor hanterar data med olika känslighet. Säkerhetsklasser avgör vilken AI-modell och miljö som får användas.", icon: "Shield" },
      { id: "sk2", label: "Lägre klass", description: "Öppen, icke-känslig information. Kan hanteras av modeller som körs hos internationella molnleverantörer.", icon: "Globe" },
      { id: "sk3", label: "Högre klass", description: "Känsliga uppgifter (persondata, sekretess). Kräver AI-modeller som körs i kontrollerade svenska miljöer.", icon: "Lock" },
      { id: "sk4", label: "Intric hanterar det", description: "I Intric ser du vilken säkerhetsklass varje modell har. Plattformen hindrar dig från att skicka fel data till fel modell.", icon: "ShieldCheck" },
    ],
  },
  {
    id: "intric-roller",
    title: "Roller i Intric",
    description: "Vem som kan göra vad i ett Intric Space.",
    category: "intric",
    steps: [
      { id: "ir1", label: "Ägare", description: "Skaparen av ett Space. Kan hantera medlemmar, ta bort resurser och ändra alla inställningar.", icon: "Crown" },
      { id: "ir2", label: "Admin", description: "Kan skapa assistenter, ladda upp kunskap och hantera det mesta — men inte ta bort Space:t eller ändra ägare.", icon: "UserCog" },
      { id: "ir3", label: "Medlem", description: "Kan använda assistenter och kunskapssamlingar i Space:t, men inte skapa nya eller ändra inställningar.", icon: "User" },
      { id: "ir4", label: "Rätt person, rätt behörighet", description: "Rollerna säkerställer att bara rätt personer kan ändra saker. Medlemmar kan tryggt använda AI utan risk att råka ändra inställningar.", icon: "ShieldCheck" },
    ],
  },
  {
    id: "intric-personlig-chatt",
    title: "Personlig chatt i Intric",
    description: "Din privata AI-chatt som ingen annan ser.",
    category: "intric",
    steps: [
      { id: "pc1", label: "Öppna personlig chatt", description: "I Intric har du en personlig chatt-vy. Här kan du prata med valfri AI-modell helt privat.", icon: "MessageCircle" },
      { id: "pc2", label: "Välj modell", description: "Du väljer vilken AI-modell du vill chatta med. Olika modeller passar olika uppgifter.", icon: "ToggleLeft" },
      { id: "pc3", label: "Konversationen är din", description: "Allt du skriver och alla svar stannar i din personliga vy. Inga kollegor kan se dina konversationer.", icon: "Lock" },
      { id: "pc4", label: "Testa och utforska", description: "Perfekt för att prova prompter, ställa frågor och lära dig — utan att påverka teamets resurser.", icon: "FlaskConical" },
    ],
  },
  {
    id: "intric-bilagor-kunskap",
    title: "Bilagor som kunskap i Intric",
    description: "Bifoga filer direkt i chatten som AI:n läser.",
    category: "intric",
    steps: [
      { id: "bk1", label: "Bifoga en fil", description: "I chatten med en Intric-assistent kan du bifoga en fil — till exempel en PDF, ett Word-dokument eller en bild.", icon: "Paperclip" },
      { id: "bk2", label: "AI:n läser filen", description: "Assistenten läser och analyserar filens innehåll direkt. Den behöver inte vara uppladdad till en kunskapssamling.", icon: "ScanText" },
      { id: "bk3", label: "Ställ frågor om filen", description: "Du kan fråga: 'Sammanfatta detta avtal' eller 'Vilka datum nämns i dokumentet?' AI:n svarar baserat på filens innehåll.", icon: "HelpCircle" },
      { id: "bk4", label: "Tillfällig kunskap", description: "Filen används bara i den konversationen — den sparas inte permanent i kunskapssamlingen om du inte väljer det.", icon: "Timer" },
    ],
  },
  {
    id: "intric-plans",
    title: "Intric-planer",
    description: "Olika abonnemangsnivåer i Intric.",
    category: "intric",
    steps: [
      { id: "pn1", label: "Free-plan", description: "Grundläggande tillgång med begränsade anrop. Perfekt för att testa och utvärdera plattformen.", icon: "Gift" },
      { id: "pn2", label: "Pro-plan", description: "Fler anrop, fler AI-modeller och mer lagringsutrymme för kunskapssamlingar. För team som använder AI dagligen.", icon: "Zap" },
      { id: "pn3", label: "Enterprise-plan", description: "Obegränsade resurser, dedikerad support och möjlighet att köra egna AI-modeller i helt isolerade miljöer.", icon: "Building" },
      { id: "pn4", label: "Välj rätt plan", description: "Kommunen väljer plan baserat på antal användare, säkerhetskrav och hur mycket AI-kapacitet som behövs.", icon: "Settings" },
    ],
  },
  {
    id: "intric-marketplace",
    title: "Intric Marketplace",
    description: "Dela och hitta färdiga AI-assistenter.",
    category: "intric",
    steps: [
      { id: "mk1", label: "Öppen marknadsplats", description: "Intric Marketplace är en plats där organisationer kan dela färdiga AI-assistenter med varandra.", icon: "Store" },
      { id: "mk2", label: "Hitta assistenter", description: "Du bläddrar bland assistenter som andra har byggt — kanske en som sammanfattar protokoll eller svarar på HR-frågor.", icon: "Search" },
      { id: "mk3", label: "Använd direkt", description: "Du kan använda en assistent direkt från Marketplace utan att bygga den själv. Den kopplas till ditt Space.", icon: "Download" },
      { id: "mk4", label: "Dela dina egna", description: "Har du byggt en bra assistent? Publicera den på Marketplace så att andra kommuner och organisationer kan använda den.", icon: "Share2" },
    ],
  },
  {
    id: "intric-arena",
    title: "Intric Arena",
    description: "Jämför AI-modeller sida vid sida.",
    category: "intric",
    steps: [
      { id: "ar1", label: "Välj modeller", description: "I Intric Arena väljer du två eller flera AI-modeller som du vill jämföra — till exempel GPT-4 och Claude.", icon: "Columns2" },
      { id: "ar2", label: "Ställ samma fråga", description: "Du skriver en fråga och den skickas till alla valda modeller samtidigt. Du ser svaren sida vid sida.", icon: "MessageSquare" },
      { id: "ar3", label: "Jämför resultat", description: "Du kan jämföra kvalitet, ton, noggrannhet och längd. Vilken modell ger bäst svar för just din typ av fråga?", icon: "Scale" },
      { id: "ar4", label: "Välj rätt modell", description: "Baserat på jämförelsen väljer du vilken modell som passar bäst för din assistent eller arbetsuppgift.", icon: "CheckCircle" },
    ],
  },
  {
    id: "intric-redacting",
    title: "Redacting i Intric",
    description: "Automatisk maskering av känslig information.",
    category: "intric",
    steps: [
      { id: "rd1", label: "Känslig data skickas", description: "Du skriver en fråga som råkar innehålla personnummer, namn eller annan känslig information.", icon: "AlertTriangle" },
      { id: "rd2", label: "Intric upptäcker", description: "Innan texten når AI-modellen skannar Intric efter känsliga uppgifter — personnummer, namn, adresser med mera.", icon: "ScanSearch" },
      { id: "rd3", label: "Information maskeras", description: "Känsliga delar ersätts med platshållare: '199001011234' blir '[PERSONNUMMER]'. AI:n ser aldrig den riktiga datan.", icon: "EyeOff" },
      { id: "rd4", label: "Svar avmaskeras", description: "När AI:n svarar sätts den riktiga informationen tillbaka. Du ser hela svaret men AI-modellen hanterade aldrig personuppgifterna.", icon: "ShieldCheck" },
    ],
  },
  {
    id: "intric-data-retention",
    title: "Datalagring i Intric",
    description: "Hur länge data sparas och hur den skyddas.",
    category: "intric",
    steps: [
      { id: "dr1", label: "Data skapas", description: "Varje gång du chattar med en assistent skapas data — din fråga, AI:ns svar och eventuella bifogade filer.", icon: "MessageSquare" },
      { id: "dr2", label: "Lagringsregler", description: "Intric har inställbara regler för hur länge data sparas. Organisationen bestämmer hur länge konversationer bevaras.", icon: "Settings" },
      { id: "dr3", label: "Automatisk rensning", description: "När lagringstiden passeras raderas data automatiskt. Ingen behöver komma ihåg att manuellt radera gammal information.", icon: "Trash2" },
      { id: "dr4", label: "GDPR-efterlevnad", description: "Datalagringsreglerna hjälper kommunen uppfylla GDPR:s krav på att inte spara personuppgifter längre än nödvändigt.", icon: "Scale" },
    ],
  },

  // ===========================================================================
  // MICROSOFT COPILOT
  // ===========================================================================
  {
    id: "m365-copilot",
    title: "Microsoft 365 Copilot",
    description: "AI-assistenten som finns inbyggd i dina Microsoft-verktyg.",
    category: "copilot",
    steps: [
      { id: "mc1", label: "Inbyggd i M365", description: "Copilot är inbyggd direkt i Word, Excel, PowerPoint, Outlook och Teams. Du behöver inte byta till ett separat AI-verktyg.", icon: "LayoutGrid" },
      { id: "mc2", label: "Förstår ditt arbete", description: "Copilot har tillgång till dina filer, mejl och kalendrar via Microsoft Graph. Den förstår din arbetskontext.", icon: "Brain" },
      { id: "mc3", label: "Be om hjälp", description: "Du skriver en instruktion i naturligt språk: 'Sammanfatta gårdagens mejl' eller 'Skapa en presentation om budgeten.'", icon: "MessageSquare" },
      { id: "mc4", label: "AI:n levererar", description: "Copilot genererar utkast, analyser eller sammanfattningar direkt i appen du arbetar i. Du redigerar och godkänner.", icon: "Sparkles" },
    ],
  },
  {
    id: "microsoft-graph",
    title: "Microsoft Graph",
    description: "Det dolda nätverket som kopplar ihop all din M365-data.",
    category: "copilot",
    steps: [
      { id: "mg1", label: "All din data", description: "Microsoft Graph är ett API som kopplar ihop dina mejl, filer, kalendrar, chattar och kontakter i Microsoft 365.", icon: "Database" },
      { id: "mg2", label: "Relationer kartläggs", description: "Graph förstår samband: vem du mejlar mest, vilka filer ni delar, vilka möten ni har — ett nätverk av relationer.", icon: "Network" },
      { id: "mg3", label: "Copilot söker här", description: "När du ber Copilot om hjälp söker den i Graph för att hitta relevanta dokument, mejl och data.", icon: "Search" },
      { id: "mg4", label: "Personliga resultat", description: "Tack vare Graph kan Copilot ge svar som är anpassade till just dig — baserat på din data och dina samarbeten.", icon: "UserCheck" },
    ],
  },
  {
    id: "semantic-index",
    title: "Semantic Index",
    description: "Copilot söker efter mening, inte bara nyckelord.",
    category: "copilot",
    steps: [
      { id: "si1", label: "Traditionell sökning", description: "Vanlig sökning matchar exakta ord. Söker du 'semester' hittar den inte dokument som bara skriver 'ledighet'.", icon: "Search" },
      { id: "si2", label: "Semantisk förståelse", description: "Semantic Index förstår innebörden. Den vet att 'semester', 'ledighet' och 'vila' handlar om samma sak.", icon: "Brain" },
      { id: "si3", label: "Indexering av M365", description: "All din data i Microsoft 365 indexeras semantiskt — filer, mejl, chattar. Betydelsen lagras som vektorer.", icon: "Layers" },
      { id: "si4", label: "Smartare svar", description: "Copilot hittar rätt information även om du inte använder exakt rätt ord. Sökningen förstår vad du menar.", icon: "Sparkles" },
    ],
  },
  {
    id: "copilot-word",
    title: "Copilot i Word",
    description: "Skriv, omformulera och sammanfatta direkt i Word.",
    category: "copilot",
    steps: [
      { id: "cw1", label: "Generera utkast", description: "Be Copilot skriva ett första utkast: 'Skriv ett tjänsteutlåtande om ny parkeringspolicy.' Du får en text att utgå från.", icon: "FileText" },
      { id: "cw2", label: "Omformulera text", description: "Markera text och be Copilot göra den mer formell, kortare eller enklare att förstå. Tonen anpassas direkt.", icon: "PenLine" },
      { id: "cw3", label: "Sammanfatta dokument", description: "Öppna ett långt dokument och be Copilot sammanfatta det. Du får de viktigaste punkterna på några rader.", icon: "ListChecks" },
      { id: "cw4", label: "Du har sista ordet", description: "Copilot föreslår — du bestämmer. Alla ändringar visas som förslag som du kan acceptera eller avvisa.", icon: "UserCheck" },
    ],
  },
  {
    id: "copilot-excel",
    title: "Copilot i Excel",
    description: "Analysera data och skapa formler med AI-hjälp.",
    category: "copilot",
    steps: [
      { id: "ce1", label: "Beskriv vad du vill", description: "Istället för att skriva komplexa formler beskriver du: 'Beräkna snittlön per avdelning' — Copilot skapar formeln.", icon: "Calculator" },
      { id: "ce2", label: "Analysera data", description: "Be Copilot hitta trender: 'Vilka månader har högst sjukfrånvaro?' Den analyserar och presenterar insikter.", icon: "BarChart3" },
      { id: "ce3", label: "Skapa diagram", description: "Copilot föreslår lämpliga diagramtyper och skapar dem åt dig baserat på din data.", icon: "PieChart" },
      { id: "ce4", label: "Formatera och strukturera", description: "Be Copilot sortera, filtrera och formatera tabeller. Det som tog 20 minuter kan göras på sekunder.", icon: "Table" },
    ],
  },
  {
    id: "copilot-powerpoint",
    title: "Copilot i PowerPoint",
    description: "Skapa presentationer från instruktioner eller dokument.",
    category: "copilot",
    steps: [
      { id: "pp1", label: "Beskriv presentationen", description: "Skriv: 'Skapa en presentation om kommunens digitaliseringsstrategi, 10 bilder.' Copilot bygger ett utkast.", icon: "Presentation" },
      { id: "pp2", label: "Från dokument", description: "Du kan peka på ett Word-dokument: 'Gör en presentation baserad på denna rapport.' Copilot extraherar nyckelinnehåll.", icon: "FileInput" },
      { id: "pp3", label: "Design och layout", description: "Copilot väljer passande layouter, bilder och ikoner. Du får en visuellt tilltalande presentation snabbt.", icon: "Palette" },
      { id: "pp4", label: "Finjustera", description: "Du justerar texter, byter bilder och anpassar. Copilot sparade dig den tyngsta delen — att börja från noll.", icon: "SlidersHorizontal" },
    ],
  },
  {
    id: "copilot-studio",
    title: "Copilot Studio",
    description: "Bygg egna AI-assistenter utan att programmera.",
    category: "copilot",
    steps: [
      { id: "cs1", label: "Visuell byggare", description: "Copilot Studio har ett grafiskt gränssnitt där du bygger AI-assistenter genom att klicka och dra — ingen kod behövs.", icon: "Blocks" },
      { id: "cs2", label: "Definiera beteende", description: "Du bestämmer vad assistenten ska kunna: svara på frågor, boka möten, leta i databaser eller guida användare.", icon: "Settings" },
      { id: "cs3", label: "Koppla datakällor", description: "Koppla assistenten till SharePoint, Dataverse eller andra system. Nu kan den svara baserat på organisationens data.", icon: "Plug" },
      { id: "cs4", label: "Publicera", description: "Publicera assistenten i Teams, på en webbsida eller i andra kanaler. Medarbetare kan börja använda den direkt.", icon: "Rocket" },
      { id: "cs5", label: "Analysera användning", description: "Copilot Studio visar statistik: vilka frågor ställs, var fastnar användare, och hur kan assistenten förbättras.", icon: "BarChart3" },
    ],
  },
  {
    id: "copilot-agenter",
    title: "Copilot-agenter",
    description: "AI-agenter som utför uppgifter självständigt åt dig.",
    category: "copilot",
    steps: [
      { id: "ca1", label: "Mer än chatt", description: "En Copilot-agent gör mer än att svara på frågor — den kan utföra hela arbetsflöden, som att ta emot och hantera ärenden.", icon: "Bot" },
      { id: "ca2", label: "Triggad av händelser", description: "Agenten kan starta automatiskt: 'När ett nytt mejl kommer till info@, analysera och kategorisera det.'", icon: "Zap" },
      { id: "ca3", label: "Steg-för-steg", description: "Agenten arbetar genom en kedja av steg: läs mejl → identifiera ärende → slå upp data → skapa svar → skicka till handläggare.", icon: "GitBranch" },
      { id: "ca4", label: "Mänsklig kontroll", description: "Vid osäkerhet stannar agenten och frågar en människa. Du kan alltid granska vad agenten gjort och korrigera.", icon: "UserCheck" },
    ],
  },
  {
    id: "copilot-kopplingar",
    title: "Copilot-kopplingar (Connectors)",
    description: "Koppla ihop Copilot med andra system och datakällor.",
    category: "copilot",
    steps: [
      { id: "ck1", label: "Behov av extern data", description: "Copilot arbetar i M365 men ibland behöver den data från andra system — ekonomisystem, HR-system, ärendehantering.", icon: "Database" },
      { id: "ck2", label: "Kopplingar installeras", description: "Copilot-kopplingar (connectors) fungerar som bryggor mellan M365 och externa system. Det finns hundratals färdiga.", icon: "Plug" },
      { id: "ck3", label: "Data flödar in", description: "Kopplingen hämtar data från det externa systemet och gör den sökbar för Copilot — precis som intern M365-data.", icon: "ArrowRightLeft" },
      { id: "ck4", label: "Smartare svar", description: "Nu kan Copilot svara på frågor som kräver data från flera system: 'Visa budgetstatus och relaterade dokument.'", icon: "Sparkles" },
    ],
  },
  {
    id: "microsoft-purview",
    title: "Microsoft Purview",
    description: "Säkerhet och efterlevnad för AI-användning.",
    category: "copilot",
    steps: [
      { id: "mp1", label: "Informationsskydd", description: "Purview klassificerar och skyddar känslig information. Dokument märks med känslighetsgrad: Offentlig, Intern, Konfidentiell.", icon: "Shield" },
      { id: "mp2", label: "Copilot respekterar regler", description: "Copilot ser bara information du har behörighet till. Känslighetsmärkning följer med — AI:n kan inte kringgå skyddet.", icon: "Lock" },
      { id: "mp3", label: "Övervakning", description: "Purview loggar hur data används av AI. Organisationen kan se vilken information som nås och av vem.", icon: "Eye" },
      { id: "mp4", label: "Efterlevnad", description: "Purview hjälper kommunen uppfylla GDPR, OSL och andra regelverk — även när AI används i arbetet.", icon: "Scale" },
    ],
  },
];
